### ISSUE TITLE
Bootstrap fails on 10.11

### ISSUE THREAD

**Issue by johndpope** [fink/fink#119]
Checking package... looks good (fink-0.38.6).
Checking system... i386-apple-darwin15.0.0
Use of uninitialized value $gcc in regexp compilation at /Users/johnpope/Downloads/fink/perlmod/Fink/Services.pm line 1347.
Use of uninitialized value $gcc in concatenation (.) or string at /Users/johnpope/Downloads/fink/perlmod/Fink/Bootstrap.pm line 164.
This system was not released at the time this Fink release was made.  Prerelease versions of Mac OS X might work with Fink, but there are
no guarantees.
Distribution: 10.11
Architecture: x86_64
Checking cc... looks good.
Checking make... looks good.
Checking head... looks good.
Verifying that installed Xcode Command Line Tools version is supported...
7.0.0.0.1.1440043355 is OK
Verifying that installed Xcode app version is supported...
Found Xcode version: 6.4 is OK.

OK, installing into '/sw'.

Creating directories...
/bin/mkdir -p -m755 /sw
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 631.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 631.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 631.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 633.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 633.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 633.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 633.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 633.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 633.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 633.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 633.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 633.
/bin/mkdir -m755 /sw/etc
/bin/mkdir -m755 /sw/etc/alternatives
/bin/mkdir -m755 /sw/etc/apt
/bin/mkdir -m755 /sw/src
/bin/mkdir -m755 /sw/fink
/bin/mkdir -m755 /sw/fink/debs
/bin/mkdir -m755 /sw/var
/bin/mkdir -m755 /sw/var/lib
/bin/mkdir -m755 /sw/var/lib/fink
/bin/mkdir -m755 /sw/fink//stable
/bin/mkdir -m755 /sw/fink//local
/bin/mkdir -m755 /sw/fink//local/main
/bin/mkdir -m755 /sw/fink//local/main/finkinfo
/bin/mkdir -m755 /sw/fink//local/main/binary-darwin-x86_64
/bin/mkdir -m755 /sw/fink//stable/main
/bin/mkdir -m755 /sw/fink//stable/main/finkinfo
/bin/mkdir -m755 /sw/fink//stable/main/binary-darwin-x86_64
/bin/mkdir -m755 /sw/fink//stable/crypto
/bin/mkdir -m755 /sw/fink//stable/crypto/finkinfo
/bin/mkdir -m755 /sw/fink//stable/crypto/binary-darwin-x86_64
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 649.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 649.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 649.
/usr/bin/sed -e "s,@ARV@,local," -e "s,@COMP@,main," -e "s,@ARCH@,x86_64," < Release > /sw/fink//local/main/binary-darwin-x86_64/Release; /usr/bin/touch /sw/fink//local/main/binary-darwin-x86_64/Packages; /usr/bin/gzip /sw/fink//local/main/binary-darwin-x86_64/Packages
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 649.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 649.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 649.
/usr/bin/sed -e "s,@ARV@,stable," -e "s,@COMP@,main," -e "s,@ARCH@,x86_64," < Release > /sw/fink//stable/main/binary-darwin-x86_64/Release; /usr/bin/touch /sw/fink//stable/main/binary-darwin-x86_64/Packages; /usr/bin/gzip /sw/fink//stable/main/binary-darwin-x86_64/Packages
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 649.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 649.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/johnpope/Downloads/fink/bootstrap line 649.
/usr/bin/sed -e "s,@ARV@,stable," -e "s,@COMP@,crypto," -e "s,@ARCH@,x86_64," < Release > /sw/fink//stable/crypto/binary-darwin-x86_64/Release; /usr/bin/touch /sw/fink//stable/crypto/binary-darwin-x86_64/Packages; /usr/bin/gzip /sw/fink//stable/crypto/binary-darwin-x86_64/Packages
Use of uninitialized value $selfupdatetrees in string eq at /Users/johnpope/Downloads/fink/bootstrap line 658.
Use of uninitialized value $selfupdatetrees in string at /Users/johnpope/Downloads/fink/bootstrap line 659.
ERROR: Can't create symlink /sw/fink/10.11

**Comment by akhansen** [comment]
Are you using the "TheCaptain" branch?  

Also, using mismatched Xcode CL Tools and Xcode.app frequently leads to build failures.

**Comment by johndpope** [comment]
https://github.com/fink/fink/tree/TheCaptain
