### ISSUE TITLE
TheCaptain - bootstrap fails for me on > phase compiling: dpkg-bootstrap-1.10.21-1221 failed

### ISSUE THREAD

**Issue by johndpope** [fink/fink#121]
### execution of PERL=/usr/bin/perl failed, exit code 1
phase compiling: dpkg-bootstrap-1.10.21-1221 failed

I retried with build tasks as 1 - same error. 
### execution of PERL=/usr/bin/perl failed, exit code 1
phase compiling: dpkg-bootstrap-1.10.21-1221 failed

I'm osx 10.11 xcode 7 beta 6

Also include the following system information:
Package manager version: 0.38.99.git
Distribution version: selfupdate-point (bootstrap), 10.11, x86_64
Trees: local/main stable/main
Xcode.app: 6.4
Xcode command-line tools: 7.0.0.0.1.1440043355
Max. Fink build jobs:  1

**Comment by johndpope** [comment]
retying with xcode 7 command line tools 
![screen shot 2015-09-09 at 10 32 27 am](https://cloud.githubusercontent.com/assets/289994/9750661/16f2b732-56de-11e5-9c52-3fe98618017c.png)
 selected

**Comment by akhansen** [comment]
How about a full build log?  And as I mentioned elsewhere, having a mismatched Xcode.app and Xcode is a recipe for disaster in builds.

**Comment by johndpope** [comment]
seems to be ticking along nicely now.

**Comment by johndpope** [comment]
< - after a lot of compiling it failed again here 

Setting up apt (0.5.4-1061) ...

Updating the list of locally available binary packages.
Scanning dists/stable/main/binary-darwin-x86_64
New package: dists/stable/main/binary-darwin-x86_64/base/apt-dev_0.5.4-1061_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/apt-shlibs_0.5.4-1061_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/apt_0.5.4-1061_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/base-files_1.9.16-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/bzip2-dev_1.0.6-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/bzip2-shlibs_1.0.6-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/bzip2_1.0.6-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/debianutils_4.4-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/dpkg-base-files_0.4-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/dpkg_1.10.21-1241_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/fink-mirrors_0.38.6.1-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/fink_0.38.99.git-20150909.0031_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/gettext-bin_0.19.3-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/gettext-doc_0.19.3-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/gzip_1.6-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libgettext8-dev_0.19.3-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libgettext8-shlibs_0.19.3-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libiconv-bin_1.14-5_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libiconv-dev_1.14-5_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libiconv_1.14-5_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libncurses5-shlibs_5.9-20110507-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libncurses5_5.9-20110507-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/ncurses_5.9-20110507-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/sensible-utils_0.0.7-4_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/tar_1.26-4_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/unzip_6.0-1_darwin-x86_64.deb
Downloading the indexes of available packages in the binary distribution.
/sw/bin/apt-get-lockwait -q update
Err http://bindist.finkmirrors.net stable/main Packages
  404 Not Found
Ign http://bindist.finkmirrors.net stable/main Release
Failed to fetch http://bindist.finkmirrors.net/10.11/dists/stable/main/binary-darwin-x86_64/Packages  404 Not Found
Reading Package Lists...
Building Dependency Tree...
E: Some index files failed to download, they have been ignored, or old ones used instead.
### execution of /sw/bin/apt-get-lockwait failed, exit code 100
WARNING: Failure while updating indexes.

ERROR: Bootstrap phase 2 failed!

**Comment by akhansen** [comment]
The bootstrap phase 2 error is a red herring here.  You've built everything successfully.

You're getting an error because we don't have a 10.11 binary distribution but fink isn't set up _not_ to try to use one.

**Comment by johndpope** [comment]
this may go against the gospel and everything anyone has ever done on source code on fink - but did you ever consider putting all the binaries into (perhaps a separate)  git repo and just allow people to git pull the latest (precompiled) files ?

**Comment by johndpope** [comment]
it's working. thanks

**Comment by akhansen** [comment]
Fink predates git, so no.
