### ISSUE TITLE
fink launch and install OpenVPN on mac os x

### ISSUE THREAD

**Issue by Mac85** [fink/fink#129]
hello I have installed fink now how to install OpenVAS?
Any command run with fink, does not work.

**Comment by akhansen** [comment]
There are two issues here:

1. Commands not working.  This is typically associated with people not having fink's environment set up by running /sw/bin/pathsetup.sh and/or not starting a new terminal session to utilize those settings.

2. Installing a package.  You can only install packages for which we have created package descriptions.  We do have an openvpn package, but I don't think we've got anything for OpenVAS.

**Comment by Mac85** [comment]
sorry I misspelled. I want to install OpenNMS
I have the folder that you say
![1](https://cloud.githubusercontent.com/assets/15186904/16345440/2b5be2aa-3a42-11e6-8bcc-6edc0dd290b8.png)

**Comment by akhansen** [comment]
Don't use screenshots.  Fink is a set of command-line tools and screenshots are pretty much useless to debug anything.  What happens if you run

**fink install opennms** 

in a terminal window?

**Comment by Mac85** [comment]
I use a Macbook Pro.
In which folder should I bring to invoke the command that you told me?

**Comment by akhansen** [comment]
The model of your machine shouldn't be relevant.

You should be able to run the command from any folder, which is why I didn't specify one.

**Comment by Mac85** [comment]
I launched the command you told me and are installing wow
I'll know soon how it went

**Comment by akhansen** [comment]
Good!  I'll close this issue out, since we addressed the command.

**Comment by Mac85** [comment]
ok thank you

**Comment by Mac85** [comment]
but after installing what are the commands to start and use it? You can provide a guide for use on mac

**Comment by nieder** [comment]
The command `fink info opennms` provides details on how to start OpenNMS.

**Comment by Mac85** [comment]
I am following this guide https://www.opennms.org/wiki/QuickStart
I have started the server, and so everything is right.
Now the guide says: Edit pg_hba.conf to Allow postgres to Authenticate
Where is pg_hba.conf ?

**Comment by akhansen** [comment]
probably somewhere in /sw/etc.  Try the following command in a terminal:

sudo dpkg -S pg_hba.conf

(you will need to enter your password)

**Comment by Mac85** [comment]
I found the file, and I changed the words of the guide

now I have to edit the postgresql.conf file
The guide says that I need to replace this flag tcpip_socket = true but I can not find it

But I who use the Mac and then I installed OpenNMS with fink, I have to make these changes as the guide says?

**Comment by akhansen** [comment]
Possibly not.  According to our package description:

$ fink info opennms
Information about 9814 packages read in 5 seconds.

opennms-1.8.16-32: Network Management System
 OpenNMS is an open-source, enterprise-level network management system
 along the lines of HP's OpenView line of network management tools, or
 IBM's Tivoli.
 .
 *** NOTE ***
 .
 This package will not work until you follow the post-installation
 instructions in /sw/share/doc/opennms/README.Darwin
 .
 Usage Notes:
 To start, stop, or restart OpenNMS, do:
 .
   sudo /sw/bin/opennms <command>
 .
 To enable OpenNMS to start upon bootup, issue the command:
 .
   sudo daemonic enable opennms
 .
 Note that for this to work properly, you must also enable PostgreSQL.

However, daemonic isn't actually working right now, so you'll need to start postgresql and opennms manually.

**Comment by Mac85** [comment]
then I launch the command and I get this

> opennms-1.8.16-32: Network Management System
 OpenNMS is an open-source, enterprise-level network management system
 along the lines of HP's OpenView line of network management tools, or
 IBM's Tivoli.
 .
 *** NOTE ***
 .
 This package will not work until you follow the post-installation
 instructions in /sw/share/doc/opennms/README.Darwin
 .
 Usage Notes:
 To start, stop, or restart OpenNMS, do:
 .
   sudo /sw/bin/opennms <command>
 .
 To enable OpenNMS to start upon bootup, issue the command:
 .
   sudo daemonic enable opennms
 .
 Note that for this to work properly, you must also enable PostgreSQL.
 .
 Web site: http://www.opennms.org/
 .
 Maintainer: Benjamin Reed <opennms@fink.raccoonfink.com>

**Comment by akhansen** [comment]
I don't know what you mean by "the command", because you removed the command that you ran, but "fink info opennms" provides information about the package, not any information about how to run it.

Maybe try running "sudo /sw/bin/opennms" like it says.

**Comment by Mac85** [comment]
> sudo: /sw/bin/opennms: command not found
In fact, the OpenNMS files in the bin folder, there

**Comment by akhansen** [comment]
I can't debug based on incomplete sentences.

**Comment by Mac85** [comment]
But there is a guide on how to configure openVPN with fink. A guide for users mac os x?

**Comment by akhansen** [comment]
No.  We assume that the developers of the packages will provide adequate documentation and we try to provide enough information to get started by using Fink.  Writing our own guides would be a waste of time and effort.

**Comment by Mac85** [comment]
following the guidance on the OpenNMS site I can not boot the server.
![1](https://cloud.githubusercontent.com/assets/15186904/16351231/6418c078-3a64-11e6-901a-953213f1413c.jpg)

I harbor in the folder /sw/bin/ and then and then launch the following command
./pgsql.sh-9.2 start

me the following warning appears, but it seems that after the server is started

> WARNING: You probably need to set your shared memory resources higher for
         PostgreSQL to function.  For more information on raising your shared
         memory settings, see:
         http://wiki.finkproject.org/index.php/Shared_Memory_Regions_on_Darwin

         I am also creating a default configuration in /etc/sysctl.conf.pg
         that contains values that will work with the default PostgreSQL 
         memory settings.  To use it, rename it to /etc/sysctl.conf (if you
         don't have one already) and reboot.

         For now, I'll try setting your sysctl to something higher and then
         running things anyways.  Good luck!  =)

kern.sysv.shmmax: 4194304
sysctl: kern.sysv.shmmax=8388608: Operation not permitted
kern.sysv.shmmin: 1
sysctl: kern.sysv.shmmin=1: Operation not permitted
kern.sysv.shmmni: 32
sysctl: kern.sysv.shmmni=64: Operation not permitted
kern.sysv.shmseg: 8
sysctl: kern.sysv.shmseg=8: Operation not permitted
kern.sysv.shmall: 1024
sysctl: kern.sysv.shmall=32768: Operation not permitted

./pgsql.sh-9.2: line 45: /etc/sysctl.conf.pg: Permission denied
Password:
server starting
MacBook-Pro-di-Luigi:bin Luigi$
