### ISSUE TITLE
InstallFink tool fails on 10.12

### ISSUE THREAD

**Issue by SpiraMira** [fink/fink#131]
Not sure if El Capitan is still a problem?  But I get a possibly related problem under 10.12 (Public Beta)
If I understand correctly a binary installer for a new "finkless" system is not available and one needs to manually build/Install. Right?  Java and Xcode command line tools and XQuartz dependencies have all been taken care of.  Also tried the manual ./bootsrap install procedures...to no avail.
Any help is appreciated ...b4 I dig into this further.  Thx in advance...

Transcript of InstallFink.tool attempt follows:

Checking package... looks good (fink-0.39.3).
Checking system... i386-apple-darwin16.0.0
Use of uninitialized value $gcc in regexp compilation at /Users/me/Downloads/fink/perlmod/Fink/Services.pm line 1348.
Use of uninitialized value $gcc in concatenation (.) or string at /Users/me/Downloads/fink/perlmod/Fink/Bootstrap.pm line 164.
This system was not released at the time this Fink release was made.  Prerelease versions of Mac OS X might work with Fink, but there are
no guarantees.
Distribution: 10.12
Architecture: x86_64
Checking cc... looks good.
Checking make... looks good.
Checking head... looks good.
Verifying that installed Xcode Command Line Tools version is supported...
8.0.0.0.1.1467399452 is OK
Verifying that installed Xcode app version is supported...
Found Xcode version: 8.0 is OK.

OK, installing into '/sw'.

Creating directories...
/bin/mkdir -p -m755 /sw
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 635.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 635.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 635.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 637.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 637.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 637.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 637.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 637.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 637.
/bin/mkdir -m755 /sw/etc
/bin/mkdir -m755 /sw/etc/alternatives
/bin/mkdir -m755 /sw/etc/apt
/bin/mkdir -m755 /sw/src
/bin/mkdir -m755 /sw/fink
/bin/mkdir -m755 /sw/fink/debs
/bin/mkdir -m755 /sw/var
/bin/mkdir -m755 /sw/var/lib
/bin/mkdir -m755 /sw/var/lib/fink
/bin/mkdir -m755 /sw/fink//stable
/bin/mkdir -m755 /sw/fink//local
/bin/mkdir -m755 /sw/fink//local/main
/bin/mkdir -m755 /sw/fink//local/main/finkinfo
/bin/mkdir -m755 /sw/fink//local/main/binary-darwin-x86_64
/bin/mkdir -m755 /sw/fink//stable/main
/bin/mkdir -m755 /sw/fink//stable/main/finkinfo
/bin/mkdir -m755 /sw/fink//stable/main/binary-darwin-x86_64
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 653.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 653.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 653.
/usr/bin/sed -e "s,@ARV@,local," -e "s,@COMP@,main," -e "s,@ARCH@,x86_64," < Release > /sw/fink//local/main/binary-darwin-x86_64/Release; /usr/bin/touch /sw/fink//local/main/binary-darwin-x86_64/Packages; /usr/bin/gzip /sw/fink//local/main/binary-darwin-x86_64/Packages
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 653.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 653.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at /Users/me/Downloads/fink/bootstrap line 653.
/usr/bin/sed -e "s,@ARV@,stable," -e "s,@COMP@,main," -e "s,@ARCH@,x86_64," < Release > /sw/fink//stable/main/binary-darwin-x86_64/Release; /usr/bin/touch /sw/fink//stable/main/binary-darwin-x86_64/Packages; /usr/bin/gzip /sw/fink//stable/main/binary-darwin-x86_64/Packages
Use of uninitialized value $selfupdatetrees in string eq at /Users/me/Downloads/fink/bootstrap line 662.
Use of uninitialized value $selfupdatetrees in string at /Users/me/Downloads/fink/bootstrap line 663.
ERROR: Can't create symlink /sw/fink/10.12

**Comment by akhansen** [comment]
We haven't set Fink up to work with 10.12 yet.

**Comment by SpiraMira** [comment]
What I am doing is obviously somewhat bleeding edge.  What is your timeline for Sierra support?  We have some scripts that depend on fink.

**Comment by highacid** [comment]
```
sudo ./bootstrap                                                                                                                                                       ⏎
Checking package... looks good (fink-0.39.2).
Checking system... i386-apple-darwin16.0.0
Use of uninitialized value $gcc in regexp compilation at /Users/kosmos/Downloads/Archive/fink-0.39.2/perlmod/Fink/Services.pm line 1348.
Use of uninitialized value $gcc in concatenation (.) or string at /Users/kosmos/Downloads/Archive/fink-0.39.2/perlmod/Fink/Bootstrap.pm line 164.
This system was not released at the time this Fink release was made.  Prerelease versions of Mac OS X might work with Fink, but there are no guarantees.
Distribution: 10.12
Architecture: x86_64

Fink must be installed and run with superuser (root) privileges. Fink can automatically try to become root when it's run from a user account. Available methods:

(1)	Use sudo
(2)	Use su
(3)	None, fink must be run as root

Choose a method: [1]
Checking cc... looks good.
Checking make... looks good.
Checking head... looks good.
Verifying that installed Xcode Command Line Tools version is supported...
8.0.0.0.1.1468684416 is OK
Verifying that installed Xcode app version is supported...
Found Xcode version: 7.3.1 is OK.

Please choose the path where Fink should be installed. Note that you will normally be able to use a binary distribution only if you choose '/sw'. [/sw]

OK, installing into '/sw'.

Creating directories...
/bin/mkdir -p -m755 /sw
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 635, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 635, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 635, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 637, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 637, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 637, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 637, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 637, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 637, <STDIN> line 2.
/bin/mkdir -m755 /sw/etc
/bin/mkdir -m755 /sw/etc/alternatives
/bin/mkdir -m755 /sw/etc/apt
/bin/mkdir -m755 /sw/src
/bin/mkdir -m755 /sw/fink
/bin/mkdir -m755 /sw/fink/debs
/bin/mkdir -m755 /sw/var
/bin/mkdir -m755 /sw/var/lib
/bin/mkdir -m755 /sw/var/lib/fink
/bin/mkdir -m755 /sw/fink//stable
/bin/mkdir -m755 /sw/fink//local
/bin/mkdir -m755 /sw/fink//local/main
/bin/mkdir -m755 /sw/fink//local/main/finkinfo
/bin/mkdir -m755 /sw/fink//local/main/binary-darwin-x86_64
/bin/mkdir -m755 /sw/fink//stable/main
/bin/mkdir -m755 /sw/fink//stable/main/finkinfo
/bin/mkdir -m755 /sw/fink//stable/main/binary-darwin-x86_64
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 653, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 653, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 653, <STDIN> line 2.
/usr/bin/sed -e "s,@ARV@,local," -e "s,@COMP@,main," -e "s,@ARCH@,x86_64," < Release > /sw/fink//local/main/binary-darwin-x86_64/Release; /usr/bin/touch /sw/fink//local/main/binary-darwin-x86_64/Packages; /usr/bin/gzip /sw/fink//local/main/binary-darwin-x86_64/Packages
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 653, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 653, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 653, <STDIN> line 2.
/usr/bin/sed -e "s,@ARV@,stable," -e "s,@COMP@,main," -e "s,@ARCH@,x86_64," < Release > /sw/fink//stable/main/binary-darwin-x86_64/Release; /usr/bin/touch /sw/fink//stable/main/binary-darwin-x86_64/Packages; /usr/bin/gzip /sw/fink//stable/main/binary-darwin-x86_64/Packages
Use of uninitialized value $selfupdatetrees in string eq at ./bootstrap line 662, <STDIN> line 2.
Use of uninitialized value $selfupdatetrees in string at ./bootstrap line 663, <STDIN> line 2.
ERROR: Can't create symlink /sw/fink/10.12

[CS@cosmicsound] ~/Downloads/Archive/fink-0.39.2
❯
```

**Comment by akhansen** [comment]
You're using a release Fink which was made before the 10.12 beta was released, so that's to be expected.

**Comment by akhansen** [comment]
That being said, we don't have 10.12 support yet in post-release, either.

**Comment by highacid** [comment]
When is expected a version for 10.12?

**Comment by akhansen** [comment]
A 10.12 version of fink will most likely be released shortly after 10.12 is in final release.  We've found that Apple often changes things around quite a bit even during the beta phase.

There is a new "sierra-alpha-bravo" branch of the fink code here on github which contains 10.12-specific changes.

**Comment by akhansen** [comment]
It's been working as far as I know.

**Comment by ChanForPres** [comment]
When will there be support for Mac OS Mojave?

**Comment by akhansen** [comment]
Posting in a closed thread (more than a year) isn't the best option for answers.  There's no fink tool for Mojave yet, but once that has been released this script can be updated to use that.
