### ISSUE TITLE
Request for FAQ/Documentation on choosing architecture.

### ISSUE THREAD

**Issue by datascienceteam01** [fink/fink#141]
There doesn't seem to be any literature on something as simple as how to select the architecture for installed packages. I need i386 support, which should work here, and I'm forced to use 64bit packages based on the premise that I'm on OSX version > 10.6
Certain applications require i386.

**Comment by akhansen** [comment]
There's no literature because we never supported that option.  Feel free to make your own fork of fink to support that option.
