### ISSUE TITLE
Fonts are squares in Freeciv

### ISSUE THREAD

**Issue by tsgl** [fink/fink#142]
Launching freeciv results in the following:

(freeciv-gtk2:55589): Pango-CRITICAL **: No modules found:
No builtin or dynamically loaded modules were found.
PangoFc will not work correctly.
This probably means there was an error in the creation of:
  '/sw/lib/pango-ft219/etc/pango/pango.modules'
You should create this file by running:
  pango-querymodules > '/sw/lib/pango-ft219/etc/pango/pango.modules'

(freeciv-gtk2:55589): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderFc', script='common'

(freeciv-gtk2:55589): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderFc', script='latin'

**Comment by dmacks** [comment]
What does "fink list pango1-xft2-ft219" say is actually installed (an "i" in the first column)? I'm going to guess you do have pango1-xft2-ft219-shlibs and maybe pango1-xft2-ft219-dev but not pango1-xft2-ft219. Try installing that last one.

**Comment by tsgl** [comment]
Oh, so obvious. That worked, thank you!

**Comment by dmacks** [comment]
I tweaked the gtk+2 package so that it's more likely that pango1 package will be installed already by the time you get to the point of running many such programs.
