### ISSUE TITLE
AppBundle install uses deprecated SplitForks that fails on non-HFS systems

### ISSUE THREAD

**Issue by nieder** [fink/fink#148]
https://github.com/fink/fink/blob/5f22e19b43c37f85c0dbc04ff81f6aaf8e64a811/perlmod/Fink/PkgVersion.pm#L3939-L3948

SplitForks was deprecated in Xcode6, and fails on an APFS (10.13) drive:
https://sourceforge.net/p/fink/mailman/message/36113627/

**Comment by akhansen** [comment]
I hate to say it, but filesystems other than case-sensitive HFS have always been pains to deal with.  Is one of those cases where the deprecated item was killed off with no alternative because "nobody uses it"?

I guess we could insert some kind of check on the filesystem type check (like `diskutil info`) to avoid fork splitting on non-HFS volumes.

In looking at this, I'm curious whether this operation changes the .deb contents depending on the build filesystem.

**Comment by kamischi** [comment]
All 3 Lazarus packages are affected by this bug. I would really be happy to have this resolved.

**Comment by nieder** [comment]
I see no indication that SplitForks does anything to an %i/Applications/ dir that has no second fork. When fed a file w/ no resource fork, SplitForks does nothing to the input file. When fed a file with a ResourceFork, it creates the file `._INPUTFILE` containing the resource fork alongside the input file. And we aren't creating anyway resource forks anyway during our build. I checked all the .app stuff that I currently have installed in %p/Applications, and none of them show a resource fork or finder info (Creator Type, etc). I also couldn't find any file on my /sw named `._*` or in the bindist search.

**Comment by nieder** [comment]
`/usr/libexec/PlistBuddy -c "Print :FilesystemType" /dev/stdin <<< $(diskutil info -plist /)` will output `apfs` or `hfs` (https://apple.stackexchange.com/a/324512)

**Comment by nieder** [comment]
This seems to work, but hard to check something that wasn't doing anything:
````
-			"\nif test -x $developer_dir/Tools/SplitForks; then $developer_dir/Tools/SplitForks '%i/Applications/'; fi";
+			"\nif [ -x $developer_dir/Tools/SplitForks -a '`/usr/libexec/PlistBuddy -c \"Print :FilesystemType\" /dev/stdin <<< $(diskutil info -plist /)`' = 'hfs' ] ; then $developer_dir/Tools/SplitForks '%i/Applications/'; fi";
````
It probably needs to be cleaned up for proper perl syntax and quoting.

**Comment by akhansen** [comment]
Ping

On my system it appears that my 10.13 update somehow toggled my filesystem over to APFS.  If I can spare some time, I can test that out.

**Comment by beren12** [comment]
> On Feb 12, 2019, at 10:16 PM, Alexander Hansen <notifications@github.com> wrote:
> 
> Ping
> 
> On my system it appears that my 10.13 update somehow toggled my filesystem over to APFS. If I can spare some time, I can test that out.

Yeah apple forces that on 10.13+. 10.14 won’t even boot off of hfs anymore, but 10.13 can.

**Comment by nieder** [comment]
Is that change for SSDs only? My Fusion drive went from 10.11 to 10.13 a month ago and it still is HFS+.

**Comment by nieder** [comment]
This was taken care of with #172.
