### ISSUE TITLE
Add `fink prefix` or `fink --prefix` to get the prefix

### ISSUE THREAD

**Issue by fingolfin** [fink/fink#149]
It would be nice if one could use `fink prefix` or `fink --prefix` and it would print `/sw` (or whatever your Fink prefix is) to stdout, similar to `brew --prefix`. This is handy for writing scripts that try to use Fink installed libraries, if installed, w.o. having to hardcode `/sw`.

**Comment by dmacks** [comment]
Sure! Either way seems reasonable; maybe ```--prefix``` is a hair easier to implement and more in keeping with the non-package-managing modes like ```--help``` and ```--version```?

**Comment by akhansen** [comment]
`--prefix` seconded.
