### ISSUE TITLE
Build-dir path leaks into qt4/qt5 .prl files

### ISSUE THREAD

**Issue by dmacks** [fink/fink#157]
Lots of Qt4 and Qt5 library packages supply a .prl file, which declares the configuration used to build the library and the flags to use to compile against it. Among them is QMAKE_PRL_BUILD_DIR, which is the directory in which the library was compiled. For example, my /sw/lib/qt4-x11/lib/libQtCore.prl begins:

```
QMAKE_PRL_BUILD_DIR = /sw/build.build/qt4-base-x11-4.7.3-140/qt-kde-qt-mac/./src/corelib
```

I have no idea what use this is, but either it's needless variation and confusion when swapping .deb among different machines or else it risks runtime contamination or variable behavior if that directory is/isn't present or doesn't match the installed library. It would be easy to have fink automatically scrub those lines as part of postinst (like we do with .la files). Or else we could have validator check for this, and require maintainers clear it in CompileScript (requires rev-up to fix existing packages). Linux seem to take the latter approach:

* http://www.linuxfromscratch.org/blfs/view/svn/x/qtwebkit5.html
* https://tests.reproducible-builds.org/debian/rb-pkg/buster/i386/qoauth.html

**Comment by nieder** [comment]
Besides the main Qt4/5 packages, the only package I can find in the bindist that has .prl files is `qca-mac/x11`. If it really is limited to this small range of packages, I assume a validator check is simpler to make than a PostInstScript scrubber. Plus a scrubber would probably have to live on forever, right?

**Comment by TheSin-** [comment]
package changes in post install scripts is a terrible idea, the .la cleaner is already a disaster, please please please stop doing that.  It has to be done before the deb is made.

**Comment by dmacks** [comment]
@nieder: Several separately-packaged libraries also have them: [list for 10.11](http://pdb.finkproject.org/pdb/filefind.php?search=prl&match_type=ends&dist_name=10.11&architecture=any&tree=any&submit=Search)

**Comment by nieder** [comment]
By 'main' I meant the Qt4/5 libraries published by the Qt company, not just qtbase. The only one there not part of Qt is qca2 (the texlive-texmf one is a false positive).

**Comment by nieder** [comment]
I'm dealing with this in updates inside the .info files. .prl files already undergo cleanup for other syntax. Killing the builddir is easy to add.

I think a validator test is the better solution.

**Comment by dmacks** [comment]
@nieder, do you have a branch where you're working on the cleanups for eventual PR, or should I do some and just push as I get them done?

**Comment by nieder** [comment]
I was updating to qt5.9 locally and cleaning the .prl files in the .infos the. But turns out that qt5.9 cannot support 10.9. So I can't commit that update :( For the time being, I need to go back to master and just push the .qrl cleanup in the qt5*.info files separately from the qt5.9 update.

**Comment by akhansen** [comment]
Maybe it's time to put 10.9 up on blocks.

**Comment by nieder** [comment]
Fixed with [6436b9bb](https://github.com/fink/fink-distributions/commit/6436b9bb0dbdd35733a1a68642075e70e0837eaf).

**Comment by nieder** [comment]
Qt4-mac/x11 are also fixed now.

**Comment by dmacks** [comment]
Thanks all!
