### ISSUE TITLE
Missing include path in qt5-qtbase

### ISSUE THREAD

**Issue by dhomeier** [fink/fink#159]
qt5-mac-qtbase_5.7.1 fails on 10.13.3 in the **Install phase** as it cannot find the path to `dbus.h` - apparently it is still doing further compilations. Setting `CPATH` in the `InstallScript` as well fixes it:

```
--- /sw/fink/10.9-libcxx/stable/main/finkinfo/libs/qt5-qtbase.info	2018-02-18 21:45:09.000000000 +0100
+++ /sw/fink/10.9-libcxx/local/main/finkinfo/libs/qt5-qtbase.info	2018-03-08 15:57:28.000000000 +0100
@@ -163,6 +163,7 @@
 
 InstallScript: <<
 	#!/bin/sh -ev
+	export CPATH=%p/include/dbus-1.0:%p/lib/dbus-1.0/include:%p/include/glib-2.0:%p/lib/glib-2.0/include:%p/include/freetype2:%p/include
 	export QT_FINK_PREFIX=%p/lib/qt5-%type_pkg[qt]
 
 	make install INSTALL_ROOT=%d
```

**Comment by dhomeier** [comment]
Tagging @nieder as the original packager - apologies as it was not clear if build failures should be reported here or in `fink-distributions`...

**Comment by nieder** [comment]
Really weird. Can you include the actual command that failed?

Package issues probably best belong in `fink-distributions`, but I'm automatically CC'd at both places, so I would see them anywhere.

**Comment by nieder** [comment]
Is your build drive (where /scratch.noindex sits) an APFS volume?

**Comment by dhomeier** [comment]
Update: I just tried switching `Buildpath` from the system disk (SSD, APFS) to a hard disk (HFS+), and there the install proceeds successfully without additional compilations!

**Comment by dhomeier** [comment]
Good timing! Looks like yet another APFS issue.

**Comment by nieder** [comment]
APFS did shrink the internal timestamp interval, so it could be a case of the build somehow thinking early stuff was built late. Closing for now.

**Comment by zoeloe** [comment]
@nieder 

trying update to qt5-mac-qtbase-5.7.1-7
This error resurfaced again now under 10.13.6 which I'm still running.
Yes, APFS filesytem.

Package manager version: 0.45.0
Distribution version: selfupdate-git Sat Dec 28 00:45:42 2019, 10.13, x86_64
Trees: local/main stable/main local/injected
Xcode.app: 10.1
Xcode command-line tools: 10.1.0.0.1.1539992718
Max. Fink build jobs:  8

In file included from ./qdbusconnection_p.h:69:
./qdbus_symbols_p.h:61:12: fatal error: 'dbus/dbus.h' file not found
#  include <dbus/dbus.h>
