### ISSUE TITLE
Upgrade bug: fink.info requires checksum method possibly not available in older fink

### ISSUE THREAD

**Issue by dmacks** [fink/fink#160]
As of fink-0.43.0, fink's own .info declares a ```Source-Checksum: SHA256``` in addition to the long-standard ```Source-MD5:``` for the fink source tarball. When building a package, fink requires that all listed source checksums match or else it fails to build the package. Version 0.43.0 is also the first release that has support for SHA256 without requiring any additional (non-```Essential```) packages to be intalled. This is problem that blocks users' attempts to upgrade from an older fink if they do not have that other package installed. See for example [[Fink-users] Unable to update fink](https://sourceforge.net/p/fink/mailman/message/36275112/).

Pinging @fingolfin (supplied recent SHA256 improvements, including ef90a7e674e67e0eb8443a4f96160d9eaf71dc12). Should we just undo the addition of this new checksum to the .in (and also the various perl/shell processors that insert it)?

**Comment by fingolfin** [comment]
Yes, and sorry for clearly not thinking tjos through far enough:-(

Though I think just removing the line in the .in should be enough, the shell/preprocessor code only substitutes a marker and is otherwise inactive.

Will you do it? Should I?

**Comment by dmacks** [comment]
I pushed removal of SHA256 from fink.info.in to master, which fixes injection. I also pushed removal of it from fink*.info in the stable tree, so users are able to upgrade in the mean time.

I agree no harm in leaving the preprocessor functionality. However, one of our packaging tools (scripts/srcdist/dist-module.sh) also appears to need it. That script uses /sbin/md5. If we want sha256, should we use /usr/bin/shasum (which is part of Apple's perl, and available as part of perl back since 5.10 or so) or /usr/bin/openssl? Either way, that script needs its error-checking improved for failure/absence of external commands.

**Comment by nieder** [comment]
I did some tests on a 3.5GB file. This is the time to get the SHA256 value (all at least 3X attempts):

/usr/bin/openssl: 20 sec
/sw/bin/openssl: 9 sec
/sw/bin/sha256deep: 20 sec
coreutils::sha256sum: 18 sec
/usr/bin/shasum: 20 sec

/usr/bin/shasum and /usr/bin/openssl seem to have similar efficiencies and similar sha capabilities (to 512). Given licenses, I would think /usr/bin/shasum is more likely to be kept around if Apple gets picky?

**Comment by akhansen** [comment]
I believe this issue has been addressed as of fink-0.43.1 .
