### ISSUE TITLE
Still no Fink for 10.14

### ISSUE THREAD

**Issue by remkos** [fink/fink#173]
Pull request #170 has been pulled into master a week ago.
But there is still no release of Fink.
Without this 10.14 users have no way to update Fink.
I think it is time to make this release.

**Comment by nieder** [comment]
I'm in the middle of making the release but had a sick kid to deal with. I should be able to do it tonight/tomorrow.
@akhansen knows and now I also know how to do releases, and this should go faster.

**Comment by nieder** [comment]
0.44.0 has been released
