### ISSUE TITLE
Xcode 10 breaks the clang virtual package

### ISSUE THREAD

**Issue by akhansen** [fink/fink#175]
`$ clang --version`
`Apple LLVM version 10.0.0 (_clang-1000.11.45.5_)`
`Target: x86_64-apple-darwin17.7.0`
`Thread model: posix`
`InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

`$ fink list -t clang`
`Scanning package description files..........`
`Information about 10716 packages read in 1 seconds.`
 `  	clang	0-0	[virtual package representing Apple's clang compiler]`

**Comment by nieder** [comment]
This is the Xcode9 output for comparison:
```
$ /usr/bin/clang -v
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by nieder** [comment]
And on Xcode10.2.1 on 10.14.5, my version output is slightly different than @akhansen 's:
```
$ /usr/bin/clang -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
I lost the underscores but my virtual package is still not created.
