### ISSUE TITLE
Update bzip2.info and generate new release

### ISSUE THREAD

**Issue by akhansen** [fink/fink#178]
fink (all versions) can't currently be bootstrapped:

- bzip.org isn't hosting a tarball any more, so downloads grab an HTML error page.

- Master mirrors are out of service.

Syncing the current version from fink-distributions would solve this, though I'm curious why that doesn't use the official sourceforge file for bzip2-1.0.6.tar.gz (https://sourceforge.net/projects/bzip2/files/) instead of hosting that ourselves?

**Comment by nieder** [comment]
See #177 also. I chose to mirror the bzip tarball that I had on hand as opposed to using the bzip2 SF site because I wasn't 100% sure of how official the bzip2 SF site was (who is cygsimple, the project owner?)

**Comment by dmacks** [comment]
Fink was in the habit of hosting own tarballs for all core/essentialish pkgs.

**Comment by nieder** [comment]
Current changes in HEAD are:
* support 10.13.6
* under-the-hood perl optimizations to fink tool

In queue that could/should go in:
* #177 to sync bzip2 and gzip with dists
* remove SplitForks on APFS volumes when installing packages with `AppBundles:

**Comment by akhansen** [comment]
I believe this has been fixed.
