### ISSUE TITLE
Way to fresh install Fink 0.44.0 w/o mirrors?  (macOs 10.14)

### ISSUE THREAD

**Issue by sterpe** [fink/fink#181]
I previously opened #180 but wasn't sure if I had done due-diligence with it. But I think I'm stuck.

`Install Fink.tool`, `./bootstrap`, and `make bootstrap` all run into the same issue with mirrors being down and the bootstrap unable to continue.  Is there currently a way to install using git similar to `selfupdate-git` or is a fresh install completely SOL at the moment?

>  Is there currently a way to install using git similar to `selfupdate-git`

Along these lines, is there a way that this could be supported, but just requires someone to create the PR if you can point me in the right direction of what needs to be done?

cc: @akhansen

**Comment by akhansen** [comment]
The mirror issue shouldn't affect bootstrap if you select the "use original source URL option".  
However, the bzip2 package description needs to be updated to point to a new original source.  That just involves a bit of time from our unpaid staff.   

You can proceed, however, if you edit 10.9-libcxx/bzip2.info in your fink source directory, comment out `Source: http://www.bzip.org/%v/%n-%v.tar.gz`, uncomment `Source: mirror:sourceforge:fink/%n-%v.tar.gz`, then use `./bootstrap`.  You might want to remove your prior `/sw` directory.

If you do go with this route, please make sure to post any download failures on this issue--please make sure to post the whole `curl` (or whatever) command and the output.

**Comment by sterpe** [comment]
When I go through `./bootstrap` I'm never getting an 'use original source URL option'.

https://gist.github.com/sterpe/d353225d4d99d7d750f5b4e37f0256a8

**Comment by nieder** [comment]
Fink 0.44.1 just got released with the bzip2 download URL fix.
https://sourceforge.net/projects/fink/files/

That should bootstrap cleanly.

**Comment by sterpe** [comment]
@nieder @akhansen Fink 0.44.1 doesn't seem to fix this for me. As I go through bootstrap I'm not seeing an option to 'use original source url'. Is there a configuration option that I need to edit prior to running `./bootstrap`?

See gist: https://gist.github.com/sterpe/5e24bbdb10e73c0429b9e4a62c6a5dfb

**Comment by sterpe** [comment]
Ah I take it back, I didn't let it go through all retries.  Thanks folks.
