### ISSUE TITLE
bootstrap failure...

### ISSUE THREAD

**Issue by FonsRademakers** [fink/fink#182]
Can't get the sensible-utils tar file from anywhere:

Default answer will be chosen in 120 seconds...
How do you want to proceed? [4]
curl --connect-timeout 30 -f -L -A 'fink/0.44.99.git' -O http://ftp.nc.debian.org/debian/pool/main/s/sensible-utils/sensible-utils_0.0.7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
### execution of curl failed, exit code 22
Downloading the file "sensible-utils_0.0.7.tar.gz" failed.

(1)	Give up
(2)	Retry the same mirror
(3)	Retry another mirror from your continent
(4)	Retry another mirror

Default answer will be chosen in 120 seconds...
How do you want to proceed? [1]
file download failed for sensible-utils_0.0.7.tar.gz of package sensible-utils-0.0.7-4

How to proceed?

Thanks, Fons.

**Comment by akhansen** [comment]
https://github.com/fink/fink-distributions/issues/389

**Comment by akhansen** [comment]
I don't have access to my Mac right now, but provided that you're using the bootstrap script directly rather than using the `Install Fink.tool` script, you should hopefully be able to work around this by editing 10.9-libcxx/sensible-utils.info in your fink checkout directory to have a source line like the following:

Source:  mirror:sourceforge:fink/%n_%v.tar.gz

or 

Source:  https://ftp.acc.umu.se/mirror/archive/ftp.sunet.se/pub/mac/fink/%n_%v.tar.gz

**Comment by nieder** [comment]
#183 moves the sources for all bootstrap files to our SF space.

**Comment by FonsRademakers** [comment]
No ncurses download fails,  repeatedly. Any ideas?

Default answer will be chosen in 120 seconds...
How do you want to proceed? [4]
curl --connect-timeout 30 -f -L -A 'fink/0.44.99.git' -O http://cfhcable.dl.sourceforge.net/sourceforge/ncurses-5.9-20110507.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   154  100   154    0     0    580      0 --:--:-- --:--:-- --:--:--   578
100   280  100   280    0     0    477      0 --:--:-- --:--:-- --:--:--   477
100 16241  100 16241    0     0  11755      0  0:00:01  0:00:01 --:--:-- 31934
100 16232  100 16232    0     0  10475      0  0:00:01  0:00:01 --:--:-- 10475
100 16228  100 16228    0     0   9395      0  0:00:01  0:00:01 --:--:--  9395
100 16229  100 16229    0     0   8577      0  0:00:01  0:00:01 --:--:--  8577
100  135k  100  135k    0     0  58096      0  0:00:02  0:00:02 --:--:--  163k
The MD5 checksum of the file is incorrect. The most likely cause for this is a corrupted or incomplete download
Expected: 96585abb270616342b0c68269a7ac155
Actual: MD5(672b38f1fec0f2cb8b9f567936b69e2d)
        SHA1(b169ff2eee969724ec0f1cda94765e22383a3d4a)
        SHA256(f5d9a8f937dac7d9b1bdd2fe08994d5e49dbd3655ac6351313222459cc6da8ba)
Downloading the file "ncurses-5.9-20110507.tgz" failed.

(1)	Give up
(2)	Retry the same mirror
(3)	Retry another mirror from your continent
(4)	Retry another mirror

Default answer will be chosen in 120 seconds...
How do you want to proceed? [1]
file download failed for ncurses-5.9-20110507.tgz of package ncurses-5.9-20110507-1

**Comment by nieder** [comment]
What's weird about this output is that neither MD5 sum shown above (96585 or 672b3) is correct. The correct MD5 is 49dc7136424f2bdd653439eda63a2375 as seen in both Git and the SF download site:
https://github.com/fink/fink/blob/master/10.9-libcxx/ncurses.info#L12
https://sourceforge.net/projects/fink/files/miscellaneous/bootstrap/

How did you get your Fink source download? Is it a git clone?

Also, the file you're trying to download from the cfhcable SF download mirror looks like a File Not Found, because the true size should be 2.8 MB.

**Comment by FonsRademakers** [comment]
Hi,

  the Fink source is a git clone of the GitHub master.

It failed identically, so I tried to change the MD5, but used erroneously one of a failed attempt. Anyway, they all failed in the same way as partial downloads. Why? I understand the mirrors are gone, but I’ve not been able to get a single clean install after that from the fixed tar balls on the SF locations.

Cheers, Fons.


> On 11 Apr 2019, at 14:11, nieder <notifications@github.com> wrote:
> 
> What's weird about this output is that neither MD5 sum shown above (96585 or 672b3) is correct. The correct MD5 is 49dc7136424f2bdd653439eda63a2375 as seen in both Git and the SF download site:
> https://github.com/fink/fink/blob/master/10.9-libcxx/ncurses.info#L12
> https://sourceforge.net/projects/fink/files/miscellaneous/bootstrap/
> 
> How did you get your Fink source download? Is it a git clone?
> 
> Also, the file you're trying to download from the cfhcable SF download mirror looks like a File Not Found, because the true size should be 2.8 MB.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------
Dr. Fons Rademakers      CERN - European Organization for Nuclear Research
Chief Research Officer   1211 Geneve 23, Switzerland
CERN openlab             Tel: +41227679248            Mobile: +41754113742
--------------------------------------------------------------------------

**Comment by akhansen** [comment]
Looks like there's a typo in ncurses.info

**$ fink fetch ncurses-5.9-20110507-1**
<output omitted>
curl --connect-timeout 30 -f -L -A 'fink/0.44.1' -O http://downloads.sourceforge.net/fink/ncurses-5.9-20110507.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   400  100   400    0     0   2898      0 --:--:-- --:--:-- --:--:--  2898
100   383  100   383    0     0   2005      0 --:--:-- --:--:-- --:--:--  2005
100 2778k  100 2778k    0     0  1243k      0  0:00:02  0:00:02 --:--:-- 2349k

**bootstrap:**
curl --connect-timeout 30 -f -L -A 'fink/0.44.99.git' -O http://downloads.sourceforge.net/ncurses-5.9-20110507.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   280  100   280    0     0   5744      0 --:--:-- --:--:-- --:--:--  5833
100 16242  100 16242    0     0  71059      0 --:--:-- --:--:-- --:--:-- 71059
100 16232  100 16232    0     0  61198      0 --:--:-- --:--:-- --:--:-- 61198
100 16230  100 16230    0     0  30234      0 --:--:-- --:--:-- --:--:-- 30234
100 16230  100 16230    0     0  26226      0 --:--:-- --:--:-- --:--:-- 26226
100  135k  100  135k    0     0   195k      0 --:--:-- --:--:-- --:--:--  195k
The MD5 checksum of the file is incorrect. The most likely cause for this is a corrupted or
incomplete download
Expected: 49dc7136424f2bdd653439eda63a2375
Actual: MD5(51fb79b317da62d85fdef1340c7696d4)
        SHA1(93d3eb3332e34f5adc398901a6d47320bd874248)
        SHA256(6e69ddd70868067be8badaecafb211ae8f1b51fec1cebaa1e161f208ca2289a8)
Downloading the file "ncurses-5.9-20110507.tgz" failed.

$ diff -Nurd Documents/gitcheckouts/fink/10.9-libcxx/ncurses.info /sw/fink/10.9-libcxx/stable/main/finkinfo/base/ncurses.info
--- Documents/gitcheckouts/fink/10.9-libcxx/ncurses.info        2019-04-11 10:21:32.935449415 -0700
+++ /sw/fink/10.9-libcxx/stable/main/finkinfo/base/ncurses.info 2018-04-17 09:04:11.327643170 -0700
@@ -3,12 +3,8 @@
 Revision: 1

 GCC: 4.0
-
-CustomMirror: <<
-       Primary: ftp://ftp.invisible-island.net/%n/
-       Secondary: http://downloads.sourceforge.net/fink/
-<<
-Source: mirror:sourceforge:ncurses-%v.tgz
+#Source: ftp://invisible-island.net/ncurses/current/ncurses-%v.tgz
+Source: mirror:sourceforge:fink/ncurses-%v.tgz
 Source-MD5: 49dc7136424f2bdd653439eda63a2375
 SourceDirectory: ncurses-5.9
 BuildDepends: fink (>= 0.13.0)

**Comment by akhansen** [comment]
Change the Source line in ncurses.info to Source: mirror:custom:ncurses-%v.tgz

**Comment by akhansen** [comment]
#184 has been merged.

**Comment by remkos** [comment]
Seems this one can be closed.

**Comment by nieder** [comment]
Should be fixed

**Comment by peytondh** [comment]
Right…works!

Thank you very much.
--
Best!
dhp
-- 
David H. Peyton, Ph.D.
Room 323B SB-1 (office behind lab)
Professor of Chemistry
Portland State University
Portland, OR  97207-0751
   peytond@pdx.edu
   503 725-3875
