### ISSUE TITLE
system-perl on 10.14.5 is v5.18.4

### ISSUE THREAD

**Issue by nieder** [fink/fink#187]
Apple bumped the perl subversion in the latest release.

**Comment by akhansen** [comment]
I quit.

No, not really.  I just updated my system to 10.14.5 so I can do some testing.  Guess we might as well hold off on doing a release until that happens.

**Comment by akhansen** [comment]
Fortunately, the system-perl* virtuals still trigger correctly, so maybe we can get by with tweaking every perlmod in sight?

**Comment by nieder** [comment]
By adding stuff into the `Distributions:` field? But how can we restrict pm5184 only to >= 10.14.5?

**Comment by nieder** [comment]
And bootstrapping is broken because we have a check on the perl version.

**Comment by akhansen** [comment]
Ugh.  Modifying bootstrap doesn't look too hard, but maybe we need a new tree for 10.14.5 and later to deal with the dependencies.
The only other option I can think of would be to rejig the perlmods such that everything normally uses a Fink Perl, but also to have separate perlmods exist that use the system's Perl if needed--like what we do for Python modules that use OS-provided functionalities.

**Comment by fingolfin** [comment]
Ugh. This is painful *sigh*

**Comment by nieder** [comment]
On the plus side, perl5184 was easy (I think) to create from perl5182.info plus a couple patches.

Since making a new tree for a specific subversion will be a pain, should we:
1) Fix Bootstrap.pm to know about 5.18.4
2) add perl5184 that's not restricted to any distribution
3) modify all existing perlmods so that they're available as FOO-pm5184 using our own perl5184
?

I think that's what @akhansen was describing??

**Comment by nieder** [comment]
#190 takes care of item 1 above.

**Comment by nieder** [comment]
I'm currently bootstrapping a possible option that lets us keep the current 10.9-libcxx tree and add a new dist (10.14.5) that will cover anything using perl5.18.4 (so 10.14.5 and up until perl changes). I think that will allow 10.14.5 to use our pm5182 packages once they've been Dist unrestricted, and we can add a new perl5184 package (if we want) that'll only be available for OS ≤ 10.14.4.

**Comment by nieder** [comment]
Running into some problems. Anyone on 10.14 before 10.14.5? Or have Xcode << 10.1 on 10.14? My 10.14.4/5 and Xcode10.1+ installs all lost /usr/lib/libgcc_s.10.4.dylib, which messes up building any of the perl51* packages. Was this dylib lost for all 10.14 users or only after Xcode10.1?

**Comment by schwehr** [comment]
Don't have it at xcode 10.1

```
xcodebuild -version
Xcode 10.1

sw_vers -productVersion
10.14.5

ls -l /usr/lib/libgcc_*
lrwxr-xr-x  1 root  wheel  15 Dec 15 06:55 /usr/lib/libgcc_s.1.dylib -> libSystem.dylib
```

**Comment by nieder** [comment]
0.45.0 dealing with new perl is out
