### ISSUE TITLE
cannot install install-info (making fink useless to me)

### ISSUE THREAD

**Issue by tschenkde** [fink/fink#216]
Unfortunately I can not install install-info, and since all/lots of packages depends on that I can not use fink:
**"fink -b install install-info"**
and 
**"sudo /opt/sw/bin/dpkg --force-all -i** /opt/sw/var/cache/apt/archives/install-info_6.5-102_darwin-x86%5f64.deb"

ends with an similar error : looks like there is lacking command "update-info-dir" ??? on my system (OSX 10.11),
Here is some related output:

Setting up install-info (6.5-102) ...
/opt/sw/var/lib/dpkg/info/install-info.postinst: line 33: update-info-dir: command not found
/opt/sw/bin/dpkg: error processing install-info (--install):
 subprocess post-installation script returned error exit status 127
Errors were encountered while processing:
 install-info

That looks not like a massive error, but:
unfortunately I have no clue (of programming)
Hopefully somebody solved this problem before.

**Comment by nieder** [comment]
`update-info-dir` is part of the install-info package. Normally, the `install-info` deb gets unpacked (including /opt/sw/sbin/update-info-dir), and then update-info-dir gets called by the setup script /opt/sw/var/lib/dpkg/info/install-info.postinst.

What's the output of the following command:
```
dpkg-deb -c /opt/sw/var/cache/apt/archives/install-info_6.5-102_darwin-x86-64.deb
```

**Comment by tschenkde** [comment]
Hello, 
The output of that (following) command is:

dpkg-deb -c /opt/sw/var/cache/apt/archives/install-info_6.5-102_darwin-x86%5f64.deb 

drwxr-xr-x root/admin        0 2017-10-02 06:57 ./
drwxr-xr-x root/admin        0 2017-10-02 06:57 ./sw/
drwxr-xr-x root/admin        0 2017-10-02 06:57 ./sw/bin/
-rwxr-xr-x root/admin   149492 2017-10-02 06:57 ./sw/bin/ginstall-info
-rwxr-xr-x root/admin     1224 2017-10-02 06:57 ./sw/bin/install-info
drwxr-xr-x root/admin        0 2017-10-02 06:57 ./sw/sbin/
-rwxr-xr-x root/admin     1711 2017-10-02 06:57 ./sw/sbin/update-info-dir
drwxr-xr-x root/admin        0 2017-10-02 06:57 ./sw/share/
drwxr-xr-x root/admin        0 2017-10-02 06:57 ./sw/share/doc/
drwxr-xr-x root/admin        0 2017-10-02 06:57 ./sw/share/doc/install-info/
-rw-r--r-- root/admin     2286 2017-10-02 06:57 ./sw/share/doc/install-info/AUTHORS
-rw-r--r-- root/admin    35147 2017-10-02 06:57 ./sw/share/doc/install-info/COPYING
-rw-r--r-- root/admin    23432 2017-10-02 06:57 ./sw/share/doc/install-info/fdl.texi
-rw-r--r-- root/admin    94377 2017-10-02 06:57 ./sw/share/doc/install-info/info-stnd.texi
-rw-r--r-- root/admin    59668 2017-10-02 06:57 ./sw/share/doc/install-info/NEWS
-rw-r--r-- root/admin     5897 2017-10-02 06:57 ./sw/share/doc/install-info/README
-rw-r--r-- root/admin     1049 2017-10-02 06:57 ./sw/share/doc/install-info/short-sample-ja.texi
-rw-r--r-- root/admin    37623 2017-10-02 06:57 ./sw/share/doc/install-info/texinfo-tex-test.texi
-rw-r--r-- root/admin   842374 2017-10-02 06:57 ./sw/share/doc/install-info/texinfo.texi
-rw-r--r-- root/admin     9953 2017-10-02 06:57 ./sw/share/doc/install-info/TODO
-rw-r--r-- root/admin     5404 2017-10-02 06:57 ./sw/share/doc/install-info/transition-plan.txt
-rw-r--r-- root/admin       87 2017-10-02 06:57 ./sw/share/doc/install-info/version-stnd.texi
-rw-r--r-- root/admin       93 2017-10-02 06:57 ./sw/share/doc/install-info/version.texi
drwxr-xr-x root/admin        0 2017-10-02 06:57 ./sw/share/man/
drwxr-xr-x root/admin        0 2017-10-02 06:57 ./sw/share/man/man1/
-rw-r--r-- root/admin     4366 2017-10-02 06:57 ./sw/share/man/man1/ginstall-info.1
-rw-r--r-- root/admin     1004 2017-10-02 06:57 ./sw/share/man/man1/install-info.1
drwxr-xr-x root/admin        0 2017-10-02 06:57 ./sw/share/man/man8/
-rw-r--r-- root/admin      920 2017-10-02 06:57 ./sw/share/man/man8/update-info-dir.8

Thanks to seek

**Comment by tschenkde** [comment]
OK, I unpacked and got a little further. I did in /opt/:
"sudo /opt/sw/bin/dpkg --force-all -X  /opt/sw/var/cache/apt/archives/install-info_6.5-102_darwin-x86%5f64.deb ."
followed by :
"fink install install-info"
A new error appears:

"
Setting up install-info (6.5-102) ...
dyld: Library not loaded: /sw/lib/libintl.8.dylib
  Referenced from: /opt/sw/bin/ginstall-info
  Reason: image not found
"
This library is not found in  "/sw/lib/" but in "/opt/sw/bin".

How to tell fink to look in the (automatically proposed) "/opt/sw" directories, 
instead of the (also existing) "/sw" directory ?

Looks as there got something wrong during first install, installing in "/sw" and "/opt/sw" in parallel, ...

**Comment by nieder** [comment]
Ahhh. you're trying to use the bindist on 10.11 while installed into  `/opt/sw`, but the bindist for 10.11 was built in the then default `/sw`. That's why /opt/sw/bin/ginstall-info is looking for /sw/lib/libintl.8.dylib. You unpacked the install-info deb from the bindist into /opt/sw, but it is looking for libraries that were in /sw when it was compiled by the bindist build machine.

Unfortunately, you're not going to be able to use `fink -b` and will have to build packages from source.

**Comment by nieder** [comment]
If this is a fresh Fink install on 10.11 and you are never going to update this machine or migrate your install to a machine running macOS 10.15 or later, you can tell Fink to instead install into /sw during the initial setup and then you'll be able to use the binary distribution.

**Comment by tschenkde** [comment]
Thanks a lot.
This machine is to old to be upgraded to 10.15, so I will do a fresh install.
Thanks a lot.
