### ISSUE TITLE
Bootstrap fails halfway through on Catalina

### ISSUE THREAD

**Issue by dashishmeister** [fink/fink#222]
Model Identifier:	MacBookPro16,3
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	1,4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB

Relevant logs 

[Terminal Saved Output.txt](https://github.com/fink/fink/files/5937056/Terminal.Saved.Output.txt)

{yes its quite long but the sauce is at the end}

**Comment by dmacks** [comment]
Key extract seems to be:
```
Downloading the indexes of available packages in the binary distribution.
/opt/sw/bin/apt-get-lockwait -q update
Err http://bindist.finkmirrors.net stable/main Packages
  404 Not Found
Ign http://bindist.finkmirrors.net stable/main Release
Failed to fetch http://bindist.finkmirrors.net/10.15/dists/stable/main/binary-darwin-x86_64/Packages  404 Not Found
Reading Package Lists...
Building Dependency Tree...
E: Some index files failed to download, they have been ignored, or old ones used instead.
### execution of /opt/sw/bin/apt-get-lockwait failed, exit code 100
WARNING: Failure while updating indexes.
```

I think there is no 10.15 bindist. Fink should probably fail more gradefully in this situation.

**Comment by nieder** [comment]
The plus side is that Fink still installed OK. If you edit `/opt/sw/etc/fink.conf`, look for the field `UseBinaryDist`, then change it's value to `false` so that Fink doesn't keep trying to use the non-existent binary distribution. Afterwards, if you run `fink selfupdate` in a new Terminal window, everything should be fine.

**Comment by dashishmeister** [comment]
> The plus side is that Fink still installed OK. If you edit `/opt/sw/etc/fink.conf`, look for the field `UseBinaryDist`, then change it's value to `false` so that Fink doesn't keep trying to use the non-existent binary distribution. Afterwards, if you run `fink selfupdate` in a new Terminal window, everything should be fine.

I only have read-only permissions for the fink.conf file

**Comment by dashishmeister** [comment]
well nvm I duplicated it and made the necessary edits
and a psa to all wannabe Fink users on Mac: _**There is no binary distribution**_
