### ISSUE TITLE
Fink Installation Error macOS Catalina

### ISSUE THREAD

**Issue by freeyonix** [fink/fink#227]
**Error Message**
```
New package: dists/stable/main/binary-darwin-x86_64/base/base-files_1.9.17-1_darwin-x86_64.deb
Downloading the indexes of available packages in the binary distribution.
/opt/sw/bin/apt-get-lockwait -q update
Err http://bindist.finkmirrors.net stable/main Packages
  404 Not Found
Get:1 http://bindist.finkmirrors.net stable/main Release [85B]
Fetched 85B in 0s (360B/s)
Failed to fetch http://bindist.finkmirrors.net/10.15/dists/stable/main/binary-darwin-x86_64/Packages  404 Not Found
Reading Package Lists...
Building Dependency Tree...
E: Some index files failed to download, they have been ignored, or old ones used instead.
### execution of /opt/sw/bin/apt-get-lockwait failed, exit code 100
WARNING: Failure while updating indexes.

ERROR: Bootstrap phase 2 failed!
```
**command line version**
```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

macOS version
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H524
```
This is a clean install of macOS, then installed Xquarz and Java required to execute the installation. Everything goes Well till it errors out. I've tried several times, but end up with same error. 
Highly appreciate your help & time
I've attached the terminal output if its any help
Thank you!

[MacCatalinaTerminalOut.txt](https://github.com/fink/fink/files/6133537/MacCatalinaTerminalOut.txt)

**Comment by nieder** [comment]
There is no binary distribution for 10.15, so the build errors out trying to download the package list. Although the build errors, your Fink install actually completed and should be usable. That bindist failure should just be a warning and not fatal so that the install ends cleanly.

You might need to run `/sw/bin/pathsetup.sh` to set up your user environment to know about Fink, but opening a new Terminal.app window should give you a functioning Fink.

**Comment by nieder** [comment]
Year old. Assuming it's working.
