### ISSUE TITLE
xquartz-2.8.0 is not detected properly

### ISSUE THREAD

**Issue by nieder** [fink/fink#230]
With the the new release of Xquartz-2.8.0, the version is not properly detected anymore because the package receipt got changed.

https://github.com/fink/fink/blob/63cca11746bbca256338edfbb86a88913d4a9e10/perlmod/Fink/VirtPackage.pm#L1674

The new receipt is `org.xquartz.X11`. The change broke the version detection for Xquartz, as well as some fink operations like recursive remove.

Locally editing VirtPackage.pm to that new receipt name fixes things. So we'll need to check both receipts.

**Comment by dmacks** [comment]
How about ```pkgutil --regexp --pkg-info ".*\.xquartz.*"```? Or should be we conservative to avoid detecting...some other xquartz-related receipt?

VirtPackages is getting pretty heavy with system calls, maybe we can re-work this parser to do the ```grep``` and ```cut``` in perl? The block for the "xcode" package does that, so we could factor out a ```version_from_pkgutil($pkgid)``` helper function.

**Comment by dmacks** [comment]
Wanna push a fix? Recursive-remove is broken because we have some packages with specially-crafted dependencies on x11 pieces, so those packages are no longer installable.

**Comment by nieder** [comment]
@dmacks I don't think there are any other xquartz packages, so wildcarding might be OK (unless both receipts accidentally manage to both be present). Otherwise, could check for file presence of org.xquartz.X11 and if absent org.macosforge.xquartz.pkg then pull out the version with pkgutil. I won't be able to do this one.
