### ISSUE TITLE
objtools-2.22-4 configure failure blocks bootstrap on M1

### ISSUE THREAD

**Issue by akhansen** [fink/fink#235]
I'll put this here for now, as it's a bootstrap blocker, but feel free to move it to fink-distributions if that's more appropriate.

The issue manifests as follows:

`...`
`checking for sys/procfs.h... no`
`checking linker --as-needed support... no`
`*** BFD does not support target arm-apple-darwin20.6.0.`
`*** Look in bfd/config.bfd for supported targets.`
`### execution of /tmp/fink.73k7b failed, exit code 1`
`phase compiling: objtools-2.22-4 failed`

Thera are a number of different _arm_ entries in _bfd/config.bfd_, so maybe a patch would work?  I'm guessing a newer version wouldn't hurt.

Package manager version: 0.45.99.git
Distribution version: selfupdate-point (bootstrap), 11.3, arm
Trees: local/main stable/main
No recognized Xcode.app installed
Xcode command-line tools: 12.5.1.0.1.1623191612
Max. Fink build jobs:  8

**Comment by nieder** [comment]
I think @dhomeier 's commit 1bcbbf6 deals with this, no?

**Comment by cooljeanius** [comment]
So fixing this would let us close #232 and #207, correct?

**Comment by dhomeier** [comment]
For the bootstrap, probably yes, assuming we are sticking with the `arm` from `uname -p` rather than `arm64` from `uname -m`. Consequently that would require various further patches to any calls of `/usr/bin/arch %m`.
Alternatively dpkg would need to be patched to accept `arm64` (and probably a number of other packages in turn), which might be in the works in #66.

**Comment by nieder** [comment]
> For the bootstrap, probably yes, assuming we are sticking with the `arm` from `uname -p` rather than `arm64` from `uname -m`. Consequently that would require various further patches to any calls of `/usr/bin/arch -arch %m`. Alternatively dpkg would need to be patched to accept `arm64` (and probably a number of other packages in turn), which might be in the works in #66.

Isn't %m officially `arm64` now? What's left here?

**Comment by nieder** [comment]
Ping
Not sure @TheSin- is seeing this and he might know.

**Comment by dhomeier** [comment]
> Isn't %m officially `arm64` now? What's left here?

I am not aware of any remaining issues with bootstrap at this point since dpkg-1.16 has been merged, and just updated to objtools-2.41-1 from fink-distributions' HEAD on arm64 without problems.

**Comment by nieder** [comment]
Closing now since it seems fixed and we can call bootstrap.
