### ISSUE TITLE
my fink can't install packages?

### ISSUE THREAD

**Issue by zbc1508** [fink/fink#249]
(base)abc~ % . /opt/sw/bin/init.sh
(base)abc~ % fink install lammpi lammpi-dev
Information about 14876 packages read in 1 seconds.
Failed: no package found for specification 'lammpi'!
(base)abc ~ % 

I want to use fink to install MPI library, but as you see above, it did't work....SOS! Even I can't use apt-get.

**Comment by nieder** [comment]
lammpi was retired upstream in 2015 and removed from Fink about 12 years ago. Its successor is openmpi, which is in Fink. To get apt-get, install the apt package.

**Comment by zbc1508** [comment]
(base)abc ~ % fink scanpackages
Updating the list of locally available binary packages.
Scanning dists/local/main/binary-darwin-arm64
Scanning dists/stable/main/binary-darwin-arm64
(base) abc ~ % sudo apt-get update
sudo: apt-get: command not found

can't use apt-get. can fink use in Mac OS based on M2 chip?

**Comment by nieder** [comment]
Yes, fink works on an M2 chip. If you've installed the `apt` package, you should have the `apt-get` command. Except it won't do much on an M2 system because there is no binary distribution for it and all packages will need to be built from source using the `fink` tool: `fink install $PKG`.

**Comment by zbc1508** [comment]
(base) abc fink-thesin % fink install $apt-get
Information about 309 packages read in 1 seconds.
Failed: no package found for specification '-get'!
(base) abc fink-thesin % fink install apt-get 
Information about 309 packages read in 0 seconds.
Failed: no package found for specification 'apt-get'!
(base) abc fink-thesin % fink update-all
Information about 309 packages read in 0 seconds.
No packages to install.
(base) abc fink-thesin % fink install $apt    
Information about 309 packages read in 0 seconds.
No packages to install.
(base) abc fink-thesin % fink install apt   
Information about 309 packages read in 0 seconds.
Failed: no package found for specification 'apt'!

I tried many times, it did't work. fink still can't install apt-get.Could you help me ?

**Comment by beren12** [comment]
There's no current bindist, you have to make your own. apt-get is installed by default it's not $apt-get. Just use fink install to build the packages you want.

**Comment by nieder** [comment]
And run `fink selfupdate` first to get an updated list of packages. Your first post lists 14876 packages, then your last post lists only 309 packages, which indicates you reinstalled Fink but didn't update the list of packages the 2nd time around.

**Comment by zbc1508** [comment]
I see.Thanks a lot!
