### ISSUE TITLE
Fink bootstrap fails on macOS 14

### ISSUE THREAD

**Issue by kristibektashi** [fink/fink#255]
After cloning the Git repository on my M2 Pro MacBook and attempting to bootstrap it, the following error occurs:

```
Argument "13.-1" isn't numeric in numeric ne (!=) at /Users/kristibek/fink/perlmod/Fink/Services.pm line 1445.
14.0 does not match the expected value of 13.-1. Please run `fink selfupdate` to download a newer version of fink at /Users/kristibek/fink/perlmod/Fink/Services.pm line 1449.
```
Here is the full log of what I did when I came across this error (the neofetch command is provided only for convenience)
```
Last login: Thu Aug 17 15:56:04 on ttys000
kristibek@Kristis-MacBook-Pro ~ % neofetch
                    'c.          kristibek@Kristis-MacBook-Pro.local 
                 ,xNMM.          ----------------------------------- 
               .OMMMMo           OS: macOS 14.0 23A5312d arm64 
               OMMM0,            Host: Mac14,9 
     .;loddo:' loolloddol;.      Kernel: 23.0.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 4 days, 5 hours, 11 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 61 (port), 87 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.9 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1512x982 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Light) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: Apple_Terminal 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: SFMono-Regular 
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M2 Pro 
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M2 Pro 
       .cooc,.    .,coo:.        Memory: 3251MiB / 16384MiB 

                                                         
                                                         


kristibek@Kristis-MacBook-Pro ~ % git clone https://github.com/fink/fink.git
Cloning into 'fink'...
remote: Enumerating objects: 36384, done.
remote: Counting objects: 100% (994/994), done.
remote: Compressing objects: 100% (479/479), done.
remote: Total 36384 (delta 572), reused 912 (delta 509), pack-reused 35390
Receiving objects: 100% (36384/36384), 11.86 MiB | 7.75 MiB/s, done.
Resolving deltas: 100% (23923/23923), done.
kristibek@Kristis-MacBook-Pro ~ % cd fink
kristibek@Kristis-MacBook-Pro fink % ./bootstrap

Fink must be installed and run with superuser (root) privileges. Fink can
automatically try to become root when it's run from a user account. Since
you're currently running this script as a normal user, the method you choose
will also be used immediately for this script. Available methods:

(1)	Use sudo
(2)	Use su
(3)	None, fink must be run as root

Choose a method: [1] 1

Password:
Checking package... looks good (fink-0.45.99.git).
Checking system... aarch64-apple-darwin23.0.0
Argument "13.-1" isn't numeric in numeric ne (!=) at /Users/kristibek/fink/perlmod/Fink/Services.pm line 1445.
14.0 does not match the expected value of 13.-1. Please run `fink selfupdate` to download a newer version of fink at /Users/kristibek/fink/perlmod/Fink/Services.pm line 1449.
kristibek@Kristis-MacBook-Pro fink % exit

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

```

**Comment by nieder** [comment]
Thanks. Looks like we need to add darwin23 so the install process knows how to deal with it. Some of that `neofetch` diagnosis is useful, but can you also give the following output:
```
sw_vers; uname a; /usr/bin/perl -v; /usr/bin/python3 --version
```

Going back to your output, `13.-1` is troubling, because that value comes from this line:
https://github.com/fink/fink/blob/ea7b51a0dc2ace8aef16b132a284dc8318ae0e7a/perlmod/Fink/Services.pm#L1536

$kernel_vers_minor is not what's expected, or `get_kernel_vers_minor()` or its parent `get_kernel_vers_long()` are failing.

**Comment by nieder** [comment]
Looking at the code more carefully, I think the problem is that we're expecting the kernel to be 2x.1.y. And that's not true right now for the macOS 14 beta. So the conditional in `Services.pm::get_darwin_equiv()` will need to be edited to explicitly separate darwin23 from darwin22.

**Comment by kristibektashi** [comment]
Here is the output of the command you asked:
```
Last login: Thu Aug 17 17:13:09 on ttys000
kristibek@Kristis-MacBook-Pro ~ % sw_vers; uname a; /usr/bin/perl -v; /usr/bin/python3 --version
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A5312d
usage: uname [-amnoprsv]

This is perl 5, version 30, subversion 3 (v5.30.3) built for darwin-thread-multi-2level
(with 2 registered patches, see perl -V for more detail)

Copyright 1987-2020, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

Python 3.9.6
kristibek@Kristis-MacBook-Pro ~ % uname -a
Darwin Kristis-MacBook-Pro.local 23.0.0 Darwin Kernel Version 23.0.0: Tue Aug  1 03:25:26 PDT 2023; root:xnu-10002.0.242.0.6~31/RELEASE_ARM64_T6020 arm64
kristibek@Kristis-MacBook-Pro ~ % exit

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

(btw you mistyped the uname command so I ran it separately)

**Comment by TheSin-** [comment]
should be `uname -a`

**Comment by TheSin-** [comment]
stupid betas using 23.0.0

**Comment by nieder** [comment]
@kristibektashi if you can, can you apply this patch to your fink.git checkout and try bootstrapping again?
[Sonomapatch.patch](https://github.com/fink/fink/files/12384848/Sonomapatch.patch)

**Comment by kristibektashi** [comment]
> @kristibektashi if you can, can you apply this patch to your fink.git checkout and try bootstrapping again? [Sonomapatch.patch](https://github.com/fink/fink/files/12384848/Sonomapatch.patch)

After applying this patch the initial error is fixed, however bootstrapping still fails while compiling the dpkg package.

Here is the full log: https://gist.github.com/kristibektashi/f9a83d570b52df17366b63223b6fe66d

Things to note:
1. I selected the default options for every question I was asked
2. Binary packages seem to have been disabled, but I guess it makes sense since it's a beta
3. Some packages had issues downloading with the default mirrors so I had to select another mirror for each package that failed. Dpkg showed an error 404 and curl exiting with error code 22 while being downloaded from the default mirror, while everything else had error code 6 (`Could not resolve host: distfiles.ber.de.eu.finkmirrors.net`). But that might just be an issue with my internet connection or firewall (the default macOS one))
4. Fink by default selects 10 cores for use with compiling packages, but some of them were efficiency cores, as opposed to performance cores, which may have caused issues

**Comment by nieder** [comment]
Thank you. Can you provide the output of `/opt/sw/src/fink.build/dpkg-bootstrap-1.19.7-1/dpkg-1.19.7/config.log` ? That should list the reason why dpkg failed to compile.

**Comment by kristibektashi** [comment]
[config.log](https://github.com/fink/fink/files/12385524/config.log)

**Comment by nieder** [comment]
Thank you.
Do you have any other install of gcc, clang or other compiler toolset installed on your system? Or do you only have the one that came with Xcode?

```
configure:3435: checking whether the C compiler works
configure:3457: gcc -g -O2 -fstack-protector -Wformat -fPIE -Wno-unused-parameter -Wno-missing-field-initializers -Wno-cast-align -Wno-format-security -D_FORTIFY_SOURCE=2 -I/opt/sw/bootstrap/include -Wl,-read_only_stubs -Wl,-bind_at_load -fPIE -Wl,-pie -L/opt/sw/bootstrap/lib/0 -L/opt/sw/bootstrap/lib -Wl,-headerpad_max_install_names conftest.c  >&5
ld: unknown options: -read_only_stubs 
```
@TheSin- since he's the one who knows dpkg and added the now failing flag `-read_only_stubs`.

For the record, that command works on 10.14.6.

**Comment by kristibektashi** [comment]
> Thank you. Do you have any other install of gcc, clang or other compiler toolset installed on your system? Or do you only have the one that came with Xcode?
> 
> ```
> configure:3435: checking whether the C compiler works
> configure:3457: gcc -g -O2 -fstack-protector -Wformat -fPIE -Wno-unused-parameter -Wno-missing-field-initializers -Wno-cast-align -Wno-format-security -D_FORTIFY_SOURCE=2 -I/opt/sw/bootstrap/include -Wl,-read_only_stubs -Wl,-bind_at_load -fPIE -Wl,-pie -L/opt/sw/bootstrap/lib/0 -L/opt/sw/bootstrap/lib -Wl,-headerpad_max_install_names conftest.c  >&5
> ld: unknown options: -read_only_stubs 
> ```
> 
> @TheSin- since he's the one who knows dpkg and added the now failing flag `-read_only_stubs`.
> 
> For the record, that command works on 10.14.6.

I have the Game Porting Toolkit installed using the Intel version of Homebrew as per the official instructions by Apple. I believe it includes a compiler. I also have Macports and the Arm version of Homebrew, but afaik they both use Xcode

**Comment by kristibektashi** [comment]
I haven't intentionally installed any other compiler toolset on my system

**Comment by TheSin-** [comment]
I will try to find time to build a 14.x boot drive so I can test.  Seeing as it's a beta ATM I'm not sure we should go changing flags just yet until we find the root cause.  It could be a bug in MacOS 14 that might be fixed before release.  I'm not sure when I'll have time over the next 2 weeks though to be honest.

**Comment by nieder** [comment]
Is there any obvious risk for @kristibektashi locally deleting that flag and continuing trying bootstrapping? I don't know what the flag is used for.

**Comment by TheSin-** [comment]
I wrote that stuff 10 years ago, I'd have to read about the flag and look at my commits honestly.  Looking at it, I'm guessing it's a speed flag?  So should be safe.  Likely reads just the stubs instead of the entire lib?

**Comment by nieder** [comment]
@kristibektashi if you run the command:
```
perl -pi -e 's|-Wl,-read_only_stubs||g' 10.9-libcxx/dpkg.info 10.9-libcxx/dpkg.patch 10.9-libcxx/dpkg-bootstrap.info
```
That'll get rid of the flag that's causing you trouble. Because `10.9-libcxx/dpkg.patch` is getting edited, you'll have to calculate it's MD5 checksum and change it in `10.9-libcxx/dpkg.info`.
However, as @TheSin- says, it's not clear yet if that flag is actually needed or just helps.

**Comment by kristibektashi** [comment]
Thanks for the info, but I would rather not do that in case it breaks something. So I guess I will wait until either the flag is fixed by Apple or you’re certain it’s not needed

Εστάλη από Outlook για iOS<https://aka.ms/o0ukef>
________________________________
Από: nieder ***@***.***>
Στάλθηκε: Sunday, August 20, 2023 12:56:37 PM
Προς: fink/fink ***@***.***>
Κοιν.: Kristibek ***@***.***>; Mention ***@***.***>
Θέμα: Re: [fink/fink] Fink bootstrap fails on macOS 14 beta (Issue #255)


@kristibektashi<https://github.com/kristibektashi> if you run the command:

perl -pi -e 's|-Wl,-read_only_stubs||g' 10.9-libcxx/dpkg.info 10.9-libcxx/dpkg.patch 10.9-libcxx/dpkg-bootstrap.info


That'll get rid of the flag that's causing you trouble. Because 10.9-libcxx/dpkg.patch is getting edited, you'll have to calculate it's MD5 checksum and change it in 10.9-libcxx/dpkg.info.
However, as @TheSin-<https://github.com/TheSin-> says, it's not clear yet if that flag is actually needed or just helps.

**Comment by nieder** [comment]
For the selection of all 10 cores vs just the efficiency or performance cores:

What's the output for the following commands. I'm not sure all of them will work because I'm working on what the internet says and am not near a mac to check correct syntax:
```
sysctl hw.ncpu
sysctl hw.perflevel0.physicalcpu
sysctl hw.perflevel0.physicalcpu_max
sysctl hw.perflevel0.logicalcpu
sysctl hw.perflevel0.logicalcpu_max
sysctl hw.perflevel1.physicalcpu
sysctl hw.perflevel1.physicalcpu_max
sysctl hw.perflevel1.logicalcpu
sysctl hw.perflevel1.logicalcpu_max
```
The first one should report the total number of cores. The perflevel0 lines should report on the performance cores, and level1 are the efficiency cores.

Nevertheless, compilation success should not be affected by the types of cores chosen. The speed will change but results should be the same.

**Comment by nieder** [comment]
After some testing, all those comands except for `sysctl hw.ncpu` fail on a 2015 iMac, so I assume that's the case with all x86_64 systems that don't have different core types.
Any attempt by Fink to pick performance cores would need to be conditionalized for arm64 systems.

**Comment by kristibektashi** [comment]
> For the selection of all 10 cores vs just the efficiency or performance cores:
> 
> What's the output for the following commands. I'm not sure all of them will work because I'm working on what the internet says and am not near a mac to check correct syntax:
> 
> ```
> sysctl hw.ncpu
> sysctl hw.perflevel0.physicalcpu
> sysctl hw.perflevel0.physicalcpu_max
> sysctl hw.perflevel0.logicalcpu
> sysctl hw.perflevel0.logicalcpu_max
> sysctl hw.perflevel1.physicalcpu
> sysctl hw.perflevel1.physicalcpu_max
> sysctl hw.perflevel1.logicalcpu
> sysctl hw.perflevel1.logicalcpu_max
> ```
> 
> The first one should report the total number of cores. The perflevel0 lines should report on the performance cores, and level1 are the efficiency cores.
> 
> Nevertheless, compilation success should not be affected by the types of cores chosen. The speed will change but results should be the same.

```
Last login: Fri Aug 25 12:14:24 on ttys000
kristibek@Kristis-MacBook-Pro ~ % sysctl hw.ncpu
sysctl hw.perflevel0.physicalcpu
sysctl hw.perflevel0.physicalcpu_max
sysctl hw.perflevel0.logicalcpu
sysctl hw.perflevel0.logicalcpu_max
sysctl hw.perflevel1.physicalcpu
sysctl hw.perflevel1.physicalcpu_max
sysctl hw.perflevel1.logicalcpu
sysctl hw.perflevel1.logicalcpu_max
hw.ncpu: 10
hw.perflevel0.physicalcpu: 6
hw.perflevel0.physicalcpu_max: 6
hw.perflevel0.logicalcpu: 6
hw.perflevel0.logicalcpu_max: 6
hw.perflevel1.physicalcpu: 4
hw.perflevel1.physicalcpu_max: 4
hw.perflevel1.logicalcpu: 4
hw.perflevel1.logicalcpu_max: 4
kristibek@Kristis-MacBook-Pro ~ % exit

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by kristibektashi** [comment]
Bootstrap still fails in the macOS 14 RC

**Comment by nieder** [comment]
@kristibektashi this is still the `-read_only_stubs` failure?

**Comment by kristibektashi** [comment]
> @kristibektashi this is still the `-read_only_stubs` failure?

Yes I believe so

**Comment by nieder** [comment]
The `-read_only_stubs` error seems to be an Xcode specific thing and not from macOS 14, because a user on 13.6/x86_64 with Xcode15 is reporting the same problem.

@TheSin- according to `man ld`, -read_only_stubs is for i386 only.

```
-read_only_stubs
             [i386 only] Makes the __IMPORT segment of a final linked images read-only.  This option makes a program slightly more secure in that the JMP instructions in the i386 fast
             stubs cannot be easily overwritten by malicious code.  The downside is the dyld must use mprotect() to temporarily make the segment writable while it is binding the stubs.
```
Seems to be an optional hardening flag?

**Comment by TheSin-** [comment]
Based on that I agree with you, sounds safe to remove

**Comment by nieder** [comment]
@kristibektashi Can you apply this patch to the source tree and try ./bootstrap again? It gets rid of the `-read_only_stubs` flag.
`patch -p1 /path/to/saved/patch`

[no-read-only-stubs.patch](https://github.com/fink/fink/files/12708269/no-read-only-stubs.patch)

**Comment by kristibektashi** [comment]
> @kristibektashi Can you apply this patch to the source tree and try ./bootstrap again? It gets rid of the `-read_only_stubs` flag. `patch -p1 /path/to/saved/patch`
> 
> [no-read-only-stubs.patch](https://github.com/fink/fink/files/12708269/no-read-only-stubs.patch)

The `patch -p1 /path/to/saved/patch` command didn't work for me (it simply got stuck and I had to use Ctrl+C to close it), however I used `git apply -p1 /path/to/saved/patch` instead and then tried bootstrapping it, and it actually worked!

Here is the terminal output (It's pretty big, mostly because clang kept spamming that `--param max-inline-insns-single=1200` is unused):
[fink-on-sonoma.log](https://github.com/fink/fink/files/12731523/fink-on-sonoma.log)

However, some mirrors are still broken and both `apt` and `apt-get` are missing. I tried to manually install `apt` but it failed. However both `dpkg` and `fink` exist and work just fine.

**Comment by gscase** [comment]
> The `patch -p1 /path/to/saved/patch` command didn't work for me (it simply got stuck and I had to use Ctrl+C to close it), […]

patch is always catching me out.  You have to do `patch -p1 </path/to/saved/patch` (note the "<").

This patch also worked for me on released Sonoma.

**Comment by kristibektashi** [comment]
Changed title since Sonoma is no longer a beta

**Comment by kristibektashi** [comment]
This has been fixed so I am closing this issue
