### ISSUE TITLE
multiple dpkg 1.19 installs can interact/interfere with each other

### ISSUE THREAD

**Issue by nieder** [fink/fink#257]
On 13.5 (x86_64) with a brand new git install, I'm getting the following error multiple times during builds. Seems to happen either at the beginning of every *Script:
```
Setting up fink-buildlock-xz-5.2.12-1 (2023.09.17-14.40.59) ...
"getters" is not defined in %Dpkg::Arch::EXPORT_TAGS at /opt/sw2/bin/dpkg-architecture line 30.
	main::BEGIN() called at /opt/sw2/bin/dpkg-architecture line 30
	eval {...} called at /opt/sw2/bin/dpkg-architecture line 30
"mappers" is not defined in %Dpkg::Arch::EXPORT_TAGS at /opt/sw2/bin/dpkg-architecture line 30.
	main::BEGIN() called at /opt/sw2/bin/dpkg-architecture line 30
	eval {...} called at /opt/sw2/bin/dpkg-architecture line 30
Can't continue after import errors at /opt/sw2/bin/dpkg-architecture line 30.
BEGIN failed--compilation aborted at /opt/sw2/bin/dpkg-architecture line 30.
Use of uninitialized value $hostarch in chomp at /opt/sw2/lib/perl5/Fink/Services.pm line 1499.
Use of uninitialized value in concatenation (.) or string at /opt/sw2/lib/perl5/Fink/PkgVersion.pm line 5560.
sudo -u fink-bld [ENV] sh -c /tmp/fink.KF32K
env LANG=C LC_ALL=C /opt/sw2/bin/tar  --no-same-owner --no-same-permissions -xvf /opt/sw/src/xz-5.2.12.tar.bz2
xz-5.2.12/
xz-5.2.12/m4/
xz-5.2.12/m4/tuklib_physmem.m4
...
```
dpkg-gensymbols also fails before the deb can be completed:
```
dpkg-gensymbols -q -pliblzma5-shlibs -P/opt/sw2/src/fink.build/root-liblzma5-shlibs-5.2.12-1 -v5.2.12 -O/opt/sw2/src/fink.build/root-liblzma5-shlibs-5.2.12-1/DEBIAN/symbols -e/opt/sw2/src/fink.build/root-liblzma5-shlibs-5.2.12-1/opt/sw2/lib/liblzma.5.dylib
Useless use of concatenation (.) or string in void context at /opt/sw/lib/perl5/Dpkg/Vendor/Ubuntu.pm line 135.
Undefined subroutine &main::debug called at /opt/sw2/bin/dpkg-gensymbols line 215.
### execution of dpkg-gensymbols failed, exit code 2
Removing runtime build-lock...
```

**Comment by TheSin-** [comment]
That looks like a new perl to me :/ I won’t have time until mid October to really look at it, but if it’s simple enough I might be able to pick at it.  But I need a system I can update first which I do not have atm

**Comment by TheSin-** [comment]
Also is this an upgrade from an older version or just install? Cause it might be a path issue and loading an older pm

**Comment by nieder** [comment]
This was a brand new install to /opt/sw2 (on a system that already had /opt/sw). Both installs were from git, but /opt/sw was a bit older (Feb 2023 vs now).
Perl here is 5.30.3, which we've had for a while.

Anyway, I was NOT sourcing /opt/sw2/bin/init.sh yet (or /opt/sw/bin/init.sh) and had the reported failure/errors. I opened a new Terminal window (still not sourcing any init.sh) and it's gone away. I'll try some more testing, but for now it might be a false report.
