### ISSUE TITLE
./inject.pl fails with: ERROR: Package is incomplete. ### sudo failed, exit code 1

### ISSUE THREAD

**Issue by kalthad** [fink/fink#262]
Hi

I am currently on MacOS 10.15 with 
```
fink --version
Package manager version: 0.45.6
Distribution version: selfupdate-rsync Wed Dec  6 14:24:57 2023, 10.15, x86_64
Trees: local/main stable/main
```
I pull the lastest commits 
```
commit 49d4f01f9f70ade5764759bd9f520dfd94966824
```
then
```
./inject.pl
sudo ./inject.pl /opt/sw
ERROR: Package is incomplete.
### sudo failed, exit code 1
```
I run 
```
fink selfupdate
fink update-all
Scanning package description files..........
Information about 16008 packages read in 4 seconds.
Can't resolve dependency "xcode (>= 4.6)" for package "qt4-base-mac-4.8.7-7" (no matching
packages/versions found)
Exiting with failure.
```
is this the problem?
Uwe Brauer

**Comment by TheSin-** [comment]
`fink list xcode` is likely returning 0.0

**Comment by kalthad** [comment]
> `fink list xcode` is likely returning 0.0

```
fink list xcode
Information about 16008 packages read in 8 seconds.
     fpc-xcode-syntax-co  1.0-2           FreePascal syntax coloring for Xcode
     latexcodec-py310     2.0.1-1         Work with LaTeX code in python
     latexcodec-py35      2.0.1-1         Work with LaTeX code in python
     latexcodec-py36      2.0.1-1         Work with LaTeX code in python
     latexcodec-py37      2.0.1-1         Work with LaTeX code in python
     latexcodec-py38      2.0.1-1         Work with LaTeX code in python
     latexcodec-py39      2.0.1-1         Work with LaTeX code in python
     xcode                0-0             [virtual package representing the developer tools]
 i   xcode.app            12.4-1          [virtual package representing Xcode]
```
how shall I proceed?

**Comment by nieder** [comment]
Commit https://github.com/fink/fink-distributions/commit/49d4f01f9f70ade5764759bd9f520dfd94966824 belongs to fink-distributions, which is the list of packages available to Fink. Getting the latest commit from fink-distributions is not going to help with the `./inject.pl` problem.

I think you're going to need to install the Apple CommandLineTools that match your Xcode.app release. Note that even if you installed them recently, system updates frequently mess up with their detection, so it's always a good idea to reinstall the CommandLineTools in those cases.

**Comment by ouboub** [comment]
> Commit [fink/fink-distributions@49d4f01](https://github.com/fink/fink-distributions/commit/49d4f01f9f70ade5764759bd9f520dfd94966824) belongs to fink-distributions, which is the list of packages available to Fink. Getting the latest commit from fink-distributions is not going to help with the `./inject.pl` problem.
> 
> I think you're going to need to install the Apple CommandLineTools that match your Xcode.app release. Note that even if you installed them recently, system updates frequently mess up with their detection, so it's always a good idea to reinstall the CommandLineTools in those cases.

ah ok thanks, ah I upgraded 10.X once because of a security warning.
so the last this  ignorant question, how do I upgrade/re-install Apple CommandLineTools 
that matches my Xcode?

**Comment by nieder** [comment]
Apple updates frequently break the receipt for having the command line tools installed, but don't fully deregister that they're installed, so `softwareupdate` still thinks they're installed when they're broken. You have to download and reinstall (I generally keep the installer around since it's not that big).

https://developer.apple.com/ -> Account -> sign in with free Apple developer account -> Software Downloads -> More (along 2nd menubar from top) ; then search for "12.4" to get the command line tools that match your Xcode.app

This is the direct link I get when I'm logged in. I don't know if it'll work w/out being logged in.

https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12.4/Command_Line_Tools_for_Xcode_12.4.dmg

**Comment by kalthad** [comment]
> Apple updates frequently break the receipt for having the command line tools installed, but don't fully deregister that they're installed, so `softwareupdate` still thinks they're installed when they're broken. You have to download and reinstall (I generally keep the installer around since it's not that big).
> 
> https://developer.apple.com/ -> Account -> sign in with free Apple developer account -> Software Downloads -> More (along 2nd menubar from top) ; then search for "12.4" to get the command line tools that match your Xcode.app
> 
> This is the direct link I get when I'm logged in. I don't know if it'll work w/out being logged in.
> 
> https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12.4/Command_Line_Tools_for_Xcode_12.4.dmg

thanks, I tried out that link (after login into  my developer account) but obtain
```
Your account can’t access this page.

There may be certain requirements to view this content.
If you’re a member of a developer program, make sure your Account Holder has agreed the latest license agreement.
```
when I enter the software download menu I can't find that particular pkg, my list ends with 
```
iPadOS 15.8
Released
October 25, 2023 
Build
19H370 
Download restore images
[iPad mini 4, iPad Air 2](https://updates.cdn-apple.com/2023FallFCS/fullrestores/042-76437/E826C2CC-D34C-405F-B582-3F877988C052/iPad_64bit_TouchID_15.8_19H370_Restore.ipsw)
19H370
```
sigh

**Comment by kalthad** [comment]
> > Apple updates frequently break the receipt for having the command line tools installed, but don't fully deregister that they're installed, so `softwareupdate` still thinks they're installed when they're broken. You have to download and reinstall (I generally keep the installer around since it's not that big).
> > https://developer.apple.com/ -> Account -> sign in with free Apple developer account -> Software Downloads -> More (along 2nd menubar from top) ; then search for "12.4" to get the command line tools that match your Xcode.app
> > This is the direct link I get when I'm logged in. I don't know if it'll work w/out being logged in.
> > https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12.4/Command_Line_Tools_for_Xcode_12.4.dmg
> 
> thanks, I tried out that link (after login into my developer account) but obtain
> 
> ```
> Your account can’t access this page.
> 
> There may be certain requirements to view this content.
> If you’re a member of a developer program, make sure your Account Holder has agreed the latest license agreement.
> ```
> 
> when I enter the software download menu I can't find that particular pkg, my list ends with
> 
> ```
> iPadOS 15.8
> Released
> October 25, 2023 
> Build
> 19H370 
> Download restore images
> [iPad mini 4, iPad Air 2](https://updates.cdn-apple.com/2023FallFCS/fullrestores/042-76437/E826C2CC-D34C-405F-B582-3F877988C052/iPad_64bit_TouchID_15.8_19H370_Restore.ipsw)
> 19H370
> ```
> 
> sigh

I found it, it was a bit more twisted than I thought, but I am currently downloading the 12.4 command line tool for Xcode, thanks

**Comment by kalthad** [comment]
> > > Apple updates frequently break the receipt for having the command line tools installed, but don't fully deregister that they're installed, so `softwareupdate` still thinks they're installed when they're broken. You have to download and reinstall (I generally keep the installer around since it's not that big).
> > > https://developer.apple.com/ -> Account -> sign in with free Apple developer account -> Software Downloads -> More (along 2nd menubar from top) ; then search for "12.4" to get the command line tools that match your Xcode.app
> > > This is the direct link I get when I'm logged in. I don't know if it'll work w/out being logged in.
> > > https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12.4/Command_Line_Tools_for_Xcode_12.4.dmg
> > 
> > 
> > thanks, I tried out that link (after login into my developer account) but obtain
> > ```
> > Your account can’t access this page.
> > 
> > There may be certain requirements to view this content.
> > If you’re a member of a developer program, make sure your Account Holder has agreed the latest license agreement.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > when I enter the software download menu I can't find that particular pkg, my list ends with
> > ```
> > iPadOS 15.8
> > Released
> > October 25, 2023 
> > Build
> > 19H370 
> > Download restore images
> > [iPad mini 4, iPad Air 2](https://updates.cdn-apple.com/2023FallFCS/fullrestores/042-76437/E826C2CC-D34C-405F-B582-3F877988C052/iPad_64bit_TouchID_15.8_19H370_Restore.ipsw)
> > 19H370
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > sigh
> 
> **I found it**, it was a bit more twisted than I thought, but I am currently downloading the 12.4 command line tool for Xcode, thanks

I install 12.4 again. I shutdown and restarted my Mac.
I even changed to the bash shell
but I still obtain 
```
sudo ./inject.pl 
Password:
ERROR: Package is incomplete.
```
I am getting desperate

**Comment by kalthad** [comment]
> > I normally just do
> > ```
> > sudo rm -rf /Library/Developer/CommandLineTools
> > xcode-select --install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which honestly fink should auto do if Xcode version is 0-0
> 
> I will try that now

That did not help

**Comment by TheSin-** [comment]
as I said in my last message I didn't think it would.  The error you are getting isn't from `fink` it must be something that `fink` is calling, meaning you are in an inconsistent state.

see
https://github.com/fink/fink/issues/262#issuecomment-1845518557

**Comment by nieder** [comment]
Found the source. This is the wrong `./inject.pl` script in fink-distributions

https://github.com/fink/fink-distributions/blob/master/inject.pl#L43-L48

@kalthad You need to run `./inject.pl` from the directory of the Fink packager source tree (https://github.com/fink/fink), not the one in the fink-distributions (which is ancient and I think was used when there were grouped point releases of the packages fink carries).

**Comment by TheSin-** [comment]
the repo does, it's where `selfupdate` pulls from, inject.pl hasn't been used since distributions have versions.

**Comment by nieder** [comment]
The Fink project has different repos for different things:

https://github.com/fink/fink : the main fink code for the package manager tool.
https://github.com/fink/fink-distributions : the code that contains the various package description files that tell the fink tool how to work with software X or software Y.

Both are constantly being updated.

**Comment by ouboub** [comment]
> The Fink project has different repos for different things:
> 
> https://github.com/fink/fink : the main fink code for the package manager tool. https://github.com/fink/fink-distributions : the code that contains the various package description files that tell the fink tool how to work with software X or software Y.
> 
> Both are constantly being updated.

ok I understand, but wouldn't it be wise to remove .inject.pl from https://github.com/fink/fink-distributions :
in order to avoid confusions?

**Comment by TheSin-** [comment]
no, because we may make a distribution again if we have a major change.  The last one was 10.9 which we are still using. but 10.7 would have be archived using it.  So it's still in use.

**Comment by ouboub** [comment]
> no, because we may make a distribution again if we have a major change. The last one was 10.9 which we are still using. but 10.7 would have be archived using it. So it's still in use.

ok, but maybe a slightly different naming to distinguish both?

**Comment by TheSin-** [comment]
in 20+ years this is the first time this has happened.  The distinguishing name is in the repo name.  I'm not opposed to renaming but all or repos using the same script name so fink-mirrors, fink-web, etc etc would all need to rename as well.

**Comment by nieder** [comment]
If you open the file /opt/sw/lib/perl5/Fink/Services.pm, around line 1447 should be a series of comparisons. If it looks like this:

https://github.com/fink/fink/blob/091e6d30de3d5abc6e30e803d6ddf09dc6a60d73/perlmod/Fink/Services.pm#L1446-L1449

with a comparison that includes 11.6 and 11.7 both against 11.5, then you should be good to upgrade from 10.15 to 11.X.

**Comment by kalthad** [comment]
> If you open the file /opt/sw/lib/perl5/Fink/Services.pm, around line 1447 should be a series of comparisons. If it looks like this:
> 
> https://github.com/fink/fink/blob/091e6d30de3d5abc6e30e803d6ddf09dc6a60d73/perlmod/Fink/Services.pm#L1446-L1449
> 
> with a comparison that includes 11.6 and 11.7 both against 11.5, then you should be good to upgrade from 10.15 to 11.X.

tanke for this detailed information.
the file in question looks in my case at line 1447 like this
```
if ($sw_vers != $darwin_osx) {
		if (($sw_vers == 11.6 && $darwin_osx == 11.5) || ($sw_vers == 11.7 && $darwin_osx == 11.5) || ($sw_vers == 12.6 && $darwin_osx == 12.5) || ($sw_vers == 12.7 && $darwin_osx == 12.5) || ($sw_vers == 13.6 && $darwin_osx == 13.5)) {
			# special cases in Big Sur, Monterey, and Ventura where it's OK to have a mismatch
		} else {
			die "$sw_vers does not match the expected value of $darwin_osx. Please run `fink selfupdate` to download a newer version of fink";
```
so that looks ok to me, right?
regards
