### ISSUE TITLE
fink man page does not list "install" command.

### ISSUE THREAD

**Issue by sth0** [fink/fink#275]
Man page has list -installed,  It has reinstall, but just not plain old install.

**Comment by nieder** [comment]
Something besides this?

https://github.com/fink/fink/blob/63fbce14caf4cbea569d4f74f4d0b20d9923cb5b/fink.8.in#L265-L274

**Comment by sth0** [comment]
I searched the man page twice for "install" and only found "reinstall".  I apologize for lack of sleep endnote searching a 3rd time.
