### ISSUE TITLE
when a package is very new, the source is not yet on a master

### ISSUE THREAD

**Issue by cooljeanius** [fink/fink#59]
Todo.md lists this as "medium" priority. It also says that "This case is very common and needs to be dealt with much better."

**Comment by cooljeanius** [comment]
`git blame` says that this was added to the original TODO in a041bbe

**Comment by nieder** [comment]
Essential packages are directly uploaded to SF when updated, and those are listed in the `Source:` field, so they're immediately available. For non-essential packages, I believe the download masters now start grabbing upstream sources when they rsync the .info tree (which was slower 17 years ago for commit a041bbe). Short of manually uploading all new sources, this is probably good enough, unless you happen to do git-selfupdate immediately after a new package is added.

**Comment by cooljeanius** [comment]
> Short of manually uploading all new sources, this is probably good enough

OK, so is it ok to close this, then?
