### ISSUE TITLE
multiarch/universal support?

### ISSUE THREAD

**Issue by cooljeanius** [fink/fink#70]
Debian Wheezy was recently released as stable, and one of the features it touts is better multiarch support: http://www.debian.org/News/2013/20130504

I'm assuming the reason Fink hasn't been universal until now is because the Debian packaging system it's based on hasn't been universal until now, is that correct? If so, now that upstream has multiarch support, does that mean that Fink could now be universal, too?

**Comment by dmacks** [comment]
Given apple is dropping 32-bit and I don't see anything else on the horizon, should we close this?

**Comment by akhansen** [comment]
Sounds good to me.
