### ISSUE TITLE
Transfer web and xml CVS module to git

### ISSUE THREAD

**Issue by fingolfin** [fink/fink#77]
Other than dists, they are basically the last thing from CVS we are still using. They should be turned into a single `web` repository, from which our website is built. Note that the "xml" and "fink" CVS modules are a strange beast... In reality, xml is a subdir of "web". But our CVSROOT/modules file contains this magic:

```
website -a !web/xml web
xml web/xml &website
fink-mirrors fink/mirror
pdb pdb &php-lib &fink &website
```

Hence, the "xml" CVS module is a virtual alias, its content consist of web/xml, plus a subdir "xml/web", which has all the content of the web module -- except web/xml... So basically it is reversing the inclusion... Bizarre. In any case, this needs to be sorted out.

One caveat is that the file currently make use of CVS keywords like `$Author$` and `$Date$`. Specifically, the XML files contain lines like

```
  <cvsid>$Id: doc.en.xml,v 1.19 2012/11/11 15:20:13 gecko2 Exp $</cvsid>
```

These are then parsed by our tools to produce output like this in the corresponding PHP file:

```
$cvs_author = 'Author: gecko2';
$cvs_date = 'Date: 2012/11/11 15:20:13';
```

Clearly, this must be reworked. @nieder suggest that using https://github.com/Autorevision/autorevision might be helpful for this.

On the long run, we may wish to consider switching to a different way to manage our website. E.g. using a static site generator like http://jekyllrb.com/ or http://middlemanapp.com/ -- or perhaps a CMS. But on the short run, this would cause us a lot of work, though.

**Comment by akhansen** [comment]
Closing this out since we're now generating the website via git.  Let's open a fresh issue if we want to update the current setup.
