### ISSUE TITLE
Bootstrap fails on 10.9

### ISSUE THREAD

**Issue by smaret** [fink/fink#93]
% sudo ./bootstrap /sw
Checking package... looks good (fink-0.35.99.git).
Checking system... i386-apple-darwin13.0.0
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/usr/include/c++/4.2.1
Use of uninitialized value $gcc in regexp compilation at /Users/smaret/Software/fink/fink/perlmod/Fink/Services.pm line 1345.
Use of uninitialized value $gcc in concatenation (.) or string at /Users/smaret/Software/fink/fink/perlmod/Fink/Bootstrap.pm line 166.
This system was not released at the time this Fink release was made.  Prerelease versions of Mac OS X might work with Fink, but there are no
guarantees.
Distribution: 10.9
Architecture: x86_64

Fink must be installed and run with superuser (root) privileges. Fink can automatically try to become root when it's run from a user account.
Available methods:

(1) Use sudo
(2) Use su
(3) None, fink must be run as root

Choose a method: [1] 
Checking cc... looks good.
Checking make... looks good.
Checking head... looks good.
Verifying that installed Xcode version is supported...
Found Xcode version: 5.0 is OK.

OK, installing into '/sw'.

Creating directories...
/bin/mkdir -p -m755 /sw
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 538, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 538, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 538, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 540, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 540, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 540, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 540, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 540, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 540, <STDIN> line 1.
/bin/mkdir -m755 /sw/etc
/bin/mkdir -m755 /sw/etc/alternatives
/bin/mkdir -m755 /sw/etc/apt
/bin/mkdir -m755 /sw/src
/bin/mkdir -m755 /sw/fink
/bin/mkdir -m755 /sw/fink/debs
/bin/mkdir -m755 /sw/var
/bin/mkdir -m755 /sw/var/lib
/bin/mkdir -m755 /sw/var/lib/fink
/bin/mkdir -m755 /sw/fink//stable
/bin/mkdir -m755 /sw/fink//local
/bin/mkdir -m755 /sw/fink//local/main
/bin/mkdir -m755 /sw/fink//local/main/finkinfo
/bin/mkdir -m755 /sw/fink//local/main/binary-darwin-x86_64
/bin/mkdir -m755 /sw/fink//stable/main
/bin/mkdir -m755 /sw/fink//stable/main/finkinfo
/bin/mkdir -m755 /sw/fink//stable/main/binary-darwin-x86_64
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 556, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 556, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 556, <STDIN> line 1.
/usr/bin/sed -e "s,@ARV@,local," -e "s,@COMP@,main," -e "s,@ARCH@,x86_64," < Release > /sw/fink//local/main/binary-darwin-x86_64/Release; /usr/bin/touch /sw/fink//local/main/binary-darwin-x86_64/Packages; /usr/bin/gzip /sw/fink//local/main/binary-darwin-x86_64/Packages
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 556, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 556, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in concatenation (.) or string at ./bootstrap line 556, <STDIN> line 1.
/usr/bin/sed -e "s,@ARV@,stable," -e "s,@COMP@,main," -e "s,@ARCH@,x86_64," < Release > /sw/fink//stable/main/binary-darwin-x86_64/Release; /usr/bin/touch /sw/fink//stable/main/binary-darwin-x86_64/Packages; /usr/bin/gzip /sw/fink//stable/main/binary-darwin-x86_64/Packages
Use of uninitialized value $selfupdatetrees in string eq at ./bootstrap line 565, <STDIN> line 1.
Use of uninitialized value $selfupdatetrees in string at ./bootstrap line 566, <STDIN> line 1.
ERROR: Can't create symlink /sw/fink/10.9

**Comment by johndpope** [comment]
this error is back in el capitan.  10.11

**Comment by akhansen** [comment]
Are you using the "TheCaptain" branch?

**Comment by akhansen** [comment]
Never mind, I just noticed #119.
